### ISSUE TITLE
[Feature Request] Area tool

### ISSUE THREAD

**Issue by delta2k** [Direwolf20-MC/JustDireThings#100]
After watching spotlight part 5. I would think it would be great to have an Area selection tool. One that when you copy 2 points too select an area and then shift click on a machine. Then it's pasted into the machine. But also resets the tool. So it doesn't make the copy and paste tool redundant. I'm asking for this. Only because I think it's harder to select an area without keep going in and out of the machines. Would make it easier for some players and me.

**Comment by Direwolf20-MC** [comment]
Its trickier than you think, since the machines don't have a real world coordinate system they use, and theres a limit to how far they can 'reach'.  I'll think about how I could implement this in a way that makes sense for players to use.

**Comment by delta2k** [comment]
thank you dire. not expecting it. but if it was a thing. it would be amazing.
