### ISSUE TITLE
when setting up an advanced clicker minecraft crash

### ISSUE THREAD

**Issue by TSSDK** [Direwolf20-MC/JustDireThings#102]
[crash-2024-07-13_15.45.45-server.txt](https://github.com/user-attachments/files/16202190/crash-2024-07-13_15.45.45-server.txt)

**Comment by Direwolf20-MC** [comment]
Can you describe how you caused this to happen?

**Comment by TSSDK** [comment]
I was just adjusting the Z coordinate and Minecraft crashed

**Comment by TSSDK** [comment]
[Minecraft NeoForge_ 1.21 - Одиночная игра 2024-07-13 16-27-22.zip](https://github.com/user-attachments/files/16202296/Minecraft.NeoForge_.1.21.-.2024-07-13.16-27-22.zip)
this also crashed my minecraft
[crash-2024-07-13_16.27.27-server.txt](https://github.com/user-attachments/files/16202301/crash-2024-07-13_16.27.27-server.txt)

**Comment by Direwolf20-MC** [comment]
Did it go overtop of some other block or something ?

**Comment by TSSDK** [comment]
> Он перекрывал какой-то другой блок или что-то в этом роде?

no

**Comment by TSSDK** [comment]
> [Minecraft NeoForge_ 1.21 - Одиночная игра 2024-07-13 16-27-22.zip](https://github.com/user-attachments/files/16202296/Minecraft.NeoForge_.1.21.-.2024-07-13.16-27-22.zip) это также привело к сбою моего minecraft [crash-2024-07-13_16.27.27-server.txt](https://github.com/user-attachments/files/16202301/crash-2024-07-13_16.27.27-server.txt)

i check it on clear version minecraft and it also crash

**Comment by micrwvae** [comment]
same issue here
server crashed when clicking on leaves w the t3 axe and leave breaker ability toggled
https://mclo.gs/9RRytjI

**Comment by micrwvae** [comment]
playing atm10 v jdt v11.8 currently
other ppl on the discord also have reported similar crashes
iirc one instance was with the celestigem hoe in a harvester pylon  but im not 100% sure on that one

**Comment by Direwolf20-MC** [comment]
That one’s fixed :)

**Comment by micrwvae** [comment]
just updated the jdt version to 0.11.11 but the server still crashes on processing a click
https://mclo.gs/kF16YlT

is there a way to manually edit the save to remove the block?

**Comment by TSSDK** [comment]
> только что обновил версию jdt до 0.11.11, но сервер по-прежнему вылетает при обработке щелчка https://mclo.gs/kF16YlT
> 
> есть ли способ вручную отредактировать сохранение, чтобы удалить блокировку?

try deleting the session.lock file in the you save or install backup

**Comment by Direwolf20-MC** [comment]
It took me a bit, but i found the issue - it'll be resolved in 0.11.12
