### ISSUE TITLE
[Bug & Suggestion] UI Elements Shouldn't Show In Certain Circumstances

### ISSUE THREAD

**Issue by roberttkahelin8** [Direwolf20-MC/JustDireThings#103]
**Versions effected (NeoForge 1.21):** 0.11.12

**Description of bug:** Some UI elements from active/passive abilities appearing even when they really shouldn't be.

Tested this bug with some armor upgrades, since they are the parts of the mod that show UI elements on screen the most.
Here are some screenshots of the issue in question: (this one is when F1 is pressed, which hides all UI, which the ui overlays in JDTs do not respect)
![uiOnF1](https://github.com/user-attachments/assets/e8e317e3-458b-45c8-a03a-6e36682c00ee)

Here is a screenshot of a UI element in creative mode, which it's placement makes no sense here, this is more of UI preference thing than a bug but is related. It's a bit of an irritant seeing it float there... Perhaps just hide it in creative mode since the upgrades that make these UI elements pop up don't help creative mode players at all:
![UIincreative](https://github.com/user-attachments/assets/616117df-6699-4501-9bea-7202031531ac)

**Probable fix for Issues described:**  Make certain UI elements disappear when they should be, by checking whether or not F1 is pressed.
Also check if the UI element should show up in Creative Mode or not, as some mods already hide UI elements that aren't useful to creative mode players and have been doing so for a while now.

**Other Observations:** It looks like the UI is always placed above where the hearts are in survival mode, which makes no sense for creative players/other non-survival modes.

Untested in spectator mode. Tested with invulnerability (which never shows it's icon in creative), fire extinguish, untested with other upgrades, probably affects them too.

Other than the UI elements not being hidden when they should be, there are no other issues with the UI overlays that I can see.

**Comment by Direwolf20-MC** [comment]
Added a feature to hide it on F1 for now :) will circle back some time to get the positioning better in creative mode.
