### ISSUE TITLE
[Bug] Upgrades can be applied to wrong Gear

### ISSUE THREAD

**Issue by micrwvae** [Direwolf20-MC/JustDireThings#104]
found that u can add upgrades to gear that doesnt support that module
![image](https://github.com/user-attachments/assets/1476658d-eb42-4820-9269-dddf3e58908b)
jdt v 0.11.12

**Comment by Direwolf20-MC** [comment]
That’s super weird! I could have sworn I was protecting against that. I’ll take a look :)

**Comment by Direwolf20-MC** [comment]
Good catch - should be fixed in the next version :) thank you!
