### ISSUE TITLE
Losing upgrades and enchantments.

### ISSUE THREAD

**Issue by NJM1564** [Direwolf20-MC/JustDireThings#105]
When combining tools to make the Paxel all upgrades and enchantments are lost. With them staying when upgrading tools I would expect that they would when combining into the paxel too.

**Comment by Direwolf20-MC** [comment]
Yea I realized that would be an issue - and I don't believe its an easy one to solve unfortunately :(.

**Comment by NJM1564** [comment]
What about doing it through a custom block? Like you did with the Mineing laser.

**Comment by Direwolf20-MC** [comment]
Yea I just hate doing a whole custom block for just 2 items :). I might see about letting you make it in the smithing table.

**Comment by NJM1564** [comment]
You could split the custom block from the Mining laser into it's own mod and use it for both mods. A general modify dire tool block might be useful. Now and in the future with your next mod. If you decide to make one. Perhaps even eventually expanding to other functions, like having upgrades for it to work as the charging gadget and power cell, giving it functionality after you fully set up the laser.

**Comment by Direwolf20-MC** [comment]
Conceptually it’s a nice idea but it would be a massive amount of work ;). I think my best chance it trying to get the paxel a smithing table recipe.

**Comment by Direwolf20-MC** [comment]
I've converted the recipes to Smithing Table recipes - they copy over the Upgrades, but not the enchants. I'll look into getting that bit working if I can :)
