### ISSUE TITLE
upgrade triggered on left click when set to custom keybind

### ISSUE THREAD

**Issue by Minecrafter8001** [Direwolf20-MC/JustDireThings#106]
title says it all
all effects will trigger on left click if you have it set to a custom bind
the custom bind does still work though

**Comment by Direwolf20-MC** [comment]
Good catch! Should be resolved in the next version :)

**Comment by Minecrafter8001** [comment]
also the custom bind still triggers when you aren't holding item

**Comment by Direwolf20-MC** [comment]
That’s intended :)

**Comment by Minecrafter8001** [comment]
it causes issues when you have more than one item bound to the same key
like i have eclipse gate and mob x-ray both bound to R
maybe you could add a button in the UI to toggle that?

**Comment by Direwolf20-MC** [comment]
I’ll look into it :)
