### ISSUE TITLE
All upgrades appear to be unavailable 

### ISSUE THREAD

**Issue by MuteTiefling** [Direwolf20-MC/JustDireThings#107]
JDT: justdirethings-0.11.12
Neo: 21.0.95

Latest:
https://gist.github.com/MuteTiefling/8348fc32be4ced5445ff9ad112bc7940

Screenshot of tool config:
![image](https://github.com/user-attachments/assets/79a50442-fc78-4491-b14f-9a3ebd8edfb6)

JDT-Common: https://gist.github.com/MuteTiefling/924abb776aa5f9b2c5c4beb770a68133

**Comment by Direwolf20-MC** [comment]
In the new version, you need to craft the ability upgrades and install them at a smithing table :).

**Comment by MuteTiefling** [comment]
Ahh, rough to lose all that on existing tools, but understandable. Thanks!

**Comment by Direwolf20-MC** [comment]
Yup - I felt like there needed to be more effort in getting those cool abilities :)

plus now pack makers can gate them a bit more
