### ISSUE TITLE
Recipe Viewer Info panels for upgrades

### ISSUE THREAD

**Issue by MuteTiefling** [Direwolf20-MC/JustDireThings#108]
Most of the upgrades are very self explanatory, but not all. Things like Earthquake, Mental Obliteration, and Stupefy are not immediately obvious what they do. And now that they're separate upgrades, I think it'd be very helpful to tell the player what they're getting themselves into.

So, I'd propose adding info panes to each of these which briefly describe what they do. 

Alternatively, it could be added as a tooltip entry on the upgrades themselves.

**Comment by Direwolf20-MC** [comment]
Tooltip is definitely planned :)

**Comment by MuteTiefling** [comment]
Awesome. Love me some built in documentation :D
