### ISSUE TITLE
Performance issue involving JDT, Polymorph, and the Smithing Table

### ISSUE THREAD

**Issue by MuteTiefling** [Direwolf20-MC/JustDireThings#109]
Full details in the link below, as I'm not sure where the issue arises from. Regular smithing table recipes are unaffected when both mods are installed. The slowdown only seems to be with JDT recipes.

https://github.com/illusivesoulworks/polymorph/issues/277

**Comment by Direwolf20-MC** [comment]
I ran a quick profiler and its mostly on the Polymorph side thats consuming the CPU resources. That said, its absolutely possible i'm doing something wrong in my recipes that is triggering that. So I'll keep this open for now until I see how the Polymorph dev responds

**Comment by Direwolf20-MC** [comment]
Made a change which should help :).  
https://github.com/Direwolf20-MC/JustDireThings/commit/5ce7860b36afab07e1d404af38e999fe9c1e60b9
