### ISSUE TITLE
Eclipse Bow Crash

### ISSUE THREAD

**Issue by Drackion** [Direwolf20-MC/JustDireThings#113]
Description:
Added Homing, Lingering & Yondu upgrades to an Eclipse bow then charged it in a creative mekanism energy cube and placed it in my hotbar, but as soon as i scrolled over to it i crashed.

Crash Report:
https://mclo.gs/k8RSpG2

**Comment by Direwolf20-MC** [comment]
Does it reliably crash or was this a one time thing?  That crash is really weird but I’ll try to look into it :)

**Comment by Drackion** [comment]
doesn't seem like a reliable crash
made a new world and no crash at all

**Comment by Direwolf20-MC** [comment]
Ok, let me know if you can find a reliable way to make that happen :).  I honestly can't see how it COULD happen, and the crash log isn't giving me much to go on :).
