### ISSUE TITLE
Netherwart handling on upgraded farmland

### ISSUE THREAD

**Issue by tkuneck** [Direwolf20-MC/JustDireThings#115]
I've only tested voidshimmer farm land, but I can plant netherwart on it and it does grow at what I assume is normal speed. It does not autoharvest when mature. Is planting netherwart expected to work with benefits of the upgraded farm land?

neoforge 21.0.133-beta
JDT 0.11.16

**Comment by Direwolf20-MC** [comment]
Hi yes :) it should work for most plants even cactus and sugarcane. 

I’ll look into why it’s not harvesting
