### ISSUE TITLE
Homing Upgrade could use a little tweaking

### ISSUE THREAD

**Issue by MuteTiefling** [Direwolf20-MC/JustDireThings#116]
Scenario: I'm in the Nether and I want to shoot that big nasty Ghast out of the sky that's pelting me with fireballs.

I pull out my trusty bow and shoot... but oops there was a zombie piglin 3 blocks behind me. My arrow flies out a good 16 blocks or so before doing a 180 and hitting said zombie in the face. 

Now I have a Ghast *and* every piglin in the nether after me. 

The Homing feature would be much better if you were to ray trace out to whatever target the player is aiming at and setting that as the homing target. As it stands, it's nearly impossible to shoot anything far from you as there's always a target closer, even if it's not bothering you (passives, etc).

**Comment by Direwolf20-MC** [comment]
I added some code so that if you're looking at a mob (You have to be looking DIRECTLY at them though) it will assign that as a the homing target when you fire. 

I'll also look at adding a "Target hostile vs passive" toggle.

**Comment by MuteTiefling** [comment]
Sweet thanks!

**Comment by Direwolf20-MC** [comment]
Also added that toggle I talked about :)

https://x.com/Direwolf20/status/1817276518479098345
