### ISSUE TITLE
Paxels voiding contents of certain block entities on break

### ISSUE THREAD

**Issue by MuteTiefling** [Direwolf20-MC/JustDireThings#120]
Bit of an odd one, and I'm not sure if it's an issue with Ars Nouveau or with Just Dire Things.

However, if I place an Arcane Platform from Ars Nouveau, and place an item in it, the following happens:
1. Break with a vanilla pick, the platform and item contained in it drop separately (expected)
2. Break with a JDT Paxel, only the platform drops. The item is voided.

This appears to happen with many ars nouveau block entities. But breaking them with vanilla tools is safe. Similarly, I haven't noticed any issues with JDT and other block entities. For example, breaking a shulker box with that same Paxel retains the items in the block. 

Versions:
ars_nouveau-1.21.0-5.0.6-all
justdirethings-0.11.20

**Comment by Direwolf20-MC** [comment]
That’s weird. What about with the JDT pickaxes ?

**Comment by MuteTiefling** [comment]
hrm, yeah those are also voiding the drops

**Comment by Direwolf20-MC** [comment]
I’ll load it up in my dev environment and check it out :)

**Comment by Direwolf20-MC** [comment]
Found it - and solved :)

**Comment by MuteTiefling** [comment]
Awesome thanks!
