### ISSUE TITLE
killing warden causes crash

### ISSUE THREAD

**Issue by Destral1** [Direwolf20-MC/JustDireThings#125]
Tried to kill a warden with this sword in an advanced clicker
![image](https://github.com/user-attachments/assets/c7c258d0-1286-478e-afdd-f45363b6d1db)
and it caused a crash
[crash-2024-08-08_07.58.19-server.txt](https://github.com/user-attachments/files/16548436/crash-2024-08-08_07.58.19-server.txt)

playing with JDT version 0.11.21 on all the mods 10-0.28

**Comment by Direwolf20-MC** [comment]
I checked with Shadows, and it was confirmed this bug is on Apotheosis's side.
