### ISSUE TITLE
Goo not spreading at all 

### ISSUE THREAD

**Issue by Nahkranoth0** [Direwolf20-MC/JustDireThings#127]
### Just Dire Things version

1.0.1

### Minecraft Version

1.21

### (Neo)Forge Version

21.0.167

### Modpack & Version

All the Mods 10 0.31

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Goo not spreading at all regardless of the material

### Steps to reproduce

1. Open the World
2. Placing and material (i've tested placing Netherite Blocks as i've crafted the Shadowpulse Goo)
3. The goo won't spread on these blocks

### Expected behaviour

The goo should've spread to the block and transform them

### Screenshots

![image](https://github.com/user-attachments/assets/187dc578-cb52-44f3-864b-cbd95ed7cccf)

### Additional information

I've tested downgrading to 0.11.22 and it works fine

**Comment by Direwolf20-MC** [comment]
Goo needs to be fed now :). 

Click on it with one of the items it was showing
