### ISSUE TITLE
Tree Feller not triggering accelerated leaf decay

### ISSUE THREAD

**Issue by NielsPilgaard** [Direwolf20-MC/JustDireThings#128]
### Just Dire Things version

1.0.1

### Minecraft Version

1.21.0

### (Neo)Forge Version

21.0.166

### Modpack & Version

Enigmatica 10 v1.8.0

### Do you have optifine or Rubidium installed?

I have other rendering based mods installed

### Describe the issue

When using the Tree Feller upgrade on a JDT Blazegold axe, leaves do not decay fast and instead follow vanilla leaf decay.  In case it matters the axe had the Silk Touch and Efficiency 4 enchants.

### Steps to reproduce

1. put Tree Feller on a Blazegold axe
2. Cut down tree
3. See leaves remain

### Expected behaviour

For the leaves to rapidly decay when the tree is gone

### Additional information

Original issue: https://github.com/EnigmaticaModpacks/Enigmatica10/issues/84

**Comment by Direwolf20-MC** [comment]
It seems to be working in my Dev Environment - could it be another mod causing it?

https://github.com/user-attachments/assets/c310d384-80ed-4008-b61f-f86344a1b0d9

**Comment by NielsPilgaard** [comment]
Yeah could be - Would you mind trying with Silk Touch + Efficiency 4 on the Axe? I forgot to mention the reporter had that 😅

**Comment by Direwolf20-MC** [comment]
You did mention it, i forgot to test with those enchants - but yea no difference. 

https://github.com/user-attachments/assets/fe6229c7-09b7-4fcd-ba4a-a6d417947ea1

**Comment by NielsPilgaard** [comment]
Oh so I did 😂 

Did you use [Accelerated Decay](https://www.curseforge.com/minecraft/mc-mods/accelerated-decay) in your test, or another leaf decay mod?

**Comment by Direwolf20-MC** [comment]
Yup thats the one :).  I looked at the modlist for the pack, and grabbed the one from it.

**Comment by NielsPilgaard** [comment]
I tested it in Enigmatica in-dev and it's working fine - thanks for the help, and sorry for taking your time 😊

**Comment by Direwolf20-MC** [comment]
Awesome :). It’s definitely possible it was only fixed in the past 2 versions. I changed how breaking works.

**Comment by NielsPilgaard** [comment]
That's reassuring :D
