### ISSUE TITLE
Tools don't seem to function properly for specific mod interactions

### ISSUE THREAD

**Issue by WhitePhant0m** [Direwolf20-MC/JustDireThings#129]
### Just Dire Things version

1.0.1

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.8

### Modpack & Version

Craftoria v0.8.0

### Do you have optifine or Rubidium installed?

I have other rendering based mods installed

### Describe the issue

Tools don't seem to work for many interactions with other mods, here's a few I've noticed so far: Paxel/Axe doesn't work for occultism logs(cloaked ones, which you need a buff for), pick/paxel doesn't work for boon of the earth enchant from apothic enchants, pick/paxel doesn't work for armor piles from Iron's Spells 'n Spellbooks(should spawn an ancient knight when broken), I've tested with other modded tools, and they work fine on these, ex. mekanism mekatool/disassembler, MI/ExI steam drill/chainsaw

### Steps to reproduce

.

### Expected behaviour

Would be nice if the tools worked for the mentioned things.

**Comment by Direwolf20-MC** [comment]
Can you try on the latest version? I fixed some of this on 1.03

**Comment by WhitePhant0m** [comment]
I'll check

**Comment by WhitePhant0m** [comment]
Boon seems to work now, but all the other ones i mentioned do not

**Comment by Direwolf20-MC** [comment]
Thanks I’ll investigate :)

**Comment by Direwolf20-MC** [comment]
I've got the spawns working for Iron's. Occultism I need to coordinate with the author on I believe.

**Comment by Direwolf20-MC** [comment]
This should be fixed now
