### ISSUE TITLE
Clickers void? filled buckets if holding a stack of buckets when clicking on a fluid container

### ISSUE THREAD

**Issue by tkuneck** [Direwolf20-MC/JustDireThings#130]
### Just Dire Things version

1.0.3

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.12

### Do you have optifine or Rubidium installed?

Yes

### Describe the issue

Advanced clicker clicking on fluid source with stack of buckets - where do the buckets go when filled?

### Steps to reproduce

I'm attempting to use the advanced clicker to click empty buckets on a bottler (from productive bees) that is filled with 10 buckets of honey. The clicker seems to work, the honey is decremented in the bottler, however the honey bucket does not appear to exist in the world. 

This works two ways:
with 2+ buckets, the filled bucket seems to disappear.
with 1 bucket, the bucket is filled, then clicks again on the bottler and places the honey in the world (I also would rather this not happen, but I could probably play games with tick times to avoid it).

So a few questions:
1. what happens with the filled buckets? If they are voided, it's unfortunate... Maybe throw them to the ground, or have a fun teleport way to move the incompatible items somewhere else?
2. can we get a way to click based on what is in the clicking inventory? So for example, only click if there is an empty bucket. It seems the filter is only based on target block/entity, not on inventory of the clicker which may change after the click.

### Expected behaviour

bucket is filled, and is dropped on the ground if incompatible with existing inventory of the clicker.

**Comment by Direwolf20-MC** [comment]
I suspect I know whats happening, and can probably make it drop in the world :)

**Comment by Direwolf20-MC** [comment]
Fixed! In short, I never expected the fake player (That does the clicking) to ever have anything except something in its main hand. But this is an example of the filled bucket going elsewhere in his inventory.  Now, it'll drop any excess items on the ground

**Comment by Nesetalis** [comment]
did this also get fixed for the version for 1.20.4 ?
