### ISSUE TITLE
Reconsider Time Crystal progression

### ISSUE THREAD

**Issue by MuteTiefling** [Direwolf20-MC/JustDireThings#133]
### Describe the feature you'd like to have added

The main issue here is that some mods make Budding Amethyst renewable. As a result, you can simply craft the budding amethyst directly, convert it to the tier 0/1 time crystal in the overworld, and break it immediately to get the crystals.

This entirely bypasses the rather neat mechanic of using Swappers to move the block through dimensions to level it up until it finally spawns crystals in the end. 

I'd suggest that as a simple fix, you make it so Budding Time Crystal Blocks don't drop anything upon breaking.

**Comment by Direwolf20-MC** [comment]
You’re definitely correct and this was something I was concerned about as well :). I think you’re right and I’ll make this change.
