### ISSUE TITLE
Celestigem Paxel appears to no longer have a crafting recipe

### ISSUE THREAD

**Issue by MuteTiefling** [Direwolf20-MC/JustDireThings#134]
### Just Dire Things version

justdirethings-1.1.0

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.23

### Modpack & Version

Enigmatica 10 in-dev

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Celestigem Paxel appears to be missing a recipe

### Steps to reproduce

1. Check recipe in EMI

### Expected behaviour

If memory serves, this used to be crafted from an axe, pick, and shovel. Now there's nothing.

### Screenshots

Celestigem
![image](https://github.com/user-attachments/assets/73e2decc-1d4f-451c-b679-3bd179bf5acc)

Eclipse Paxel still craftable from smithing, but not 3x3
![image](https://github.com/user-attachments/assets/9ad92211-9d92-4049-80b2-5424607439f7)
![image](https://github.com/user-attachments/assets/f2b43fb6-ae0c-4b03-b218-3960106362f6)

**Comment by TheBedrockMaster** [comment]
I believe the recipe still exists, it just doesn't show in EMI
![image](https://github.com/user-attachments/assets/efb052cb-6ad3-4af1-889d-eaa2f4026e56)

**Comment by MuteTiefling** [comment]
Yeah, that does work, just isn't showing in EMI.

**Comment by MuteTiefling** [comment]
Are you classifying this as an EMI issue? Or it's fixed in dev and just pending release?
