### ISSUE TITLE
A server command to clear active portals from the servers `/dire portal clear`

### ISSUE THREAD

**Issue by 2chriswy** [Direwolf20-MC/JustDireThings#137]
### Describe the feature you'd like to have added

Can a server command be added to clear active portals from the server with a basic command as inactive players portals can be problematic?
 `/dire portal clear`

**Comment by Direwolf20-MC** [comment]
The portals are entities, so you should be able to /kill them.  /kill the justdirethings:portalentity type (something like that)

**Comment by 2chriswy** [comment]
many thanks
