### ISSUE TITLE
Missing texture for Time Protection in chestplate's settings(?)

### ISSUE THREAD

**Issue by SubordinalBlue** [Direwolf20-MC/JustDireThings#139]
### Just Dire Things version

1.1.1

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.27

### Modpack & Version

Craftoria 0.9.2

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Missing texture where Time Procection should be in Ecllipse chestplate settings

### Steps to reproduce

Open chestplate settings (cropped screenshot attached)

### Screenshots

![image](https://github.com/user-attachments/assets/8e2e3ddf-266a-46f6-8787-8b53f54541e9)

### Additional information

Note, the `Time Protection` upgrade itself, as an item shown in EMI, player's inventory, or the Smithing Table UI, displays just fine.

[ edited to correct Craftoria version to 0.9.2 ]

**Comment by Direwolf20-MC** [comment]
LOL not sure how I missed that - thank you resolved now :)
