### ISSUE TITLE
"Missing" Item Tags

### ISSUE THREAD

**Issue by TheBedrockMaster** [Direwolf20-MC/JustDireThings#140]
### Describe the feature you'd like to have added

The following items should have the following tags:

Bows: `c:tools/bow,` `c:tools/ranged_weapon`
Paxels: `c:tools/melee_weapon,` `c:tools/mining_tool,` `c:tools/paxel`
Swords, Axes: `c:tools/melee_weapon`
Primal Coal Block, Blaze Ember Block, Voidflame Coal Block, Eclipse Ember Coal Block: `c:storage_blocks`
Primal Coal Block: `c:storage_blocks/primal_coal`
Blaze Ember Block: `c:storage_blocks/blaze_ember`
Ferricore Block: `c:storage_blocks/ferricore`
Blazegold Block: `c:storage_blocks/blazegold`
Celestigem Block: `c:storage_blocks/eclipse_alloy`
Voidflame Coal Block: `c:storage_blocks/voidflame_coal`
Eclipse Ember Block: `c:storage_blocks/eclipse_ember`
Celestigem: `c:gems/celestigem`

**Comment by Direwolf20-MC** [comment]
I've added the main ones, but didn't feel the need to add tags for each of my resources :). If theres a real need I'll reconsider it.
