### ISSUE TITLE
Color choices for the AOE ‘holograms’

### ISSUE THREAD

**Issue by SubordinalBlue** [Direwolf20-MC/JustDireThings#141]
### Describe the feature you'd like to have added

I find the swappers pretty cool as personal teleporters around a large base, or as a waystone-ish alternative to get… anywhere.
I think it would be cool if the advanced swappers had selectable colors for their AOE renders, synced across matched pairs, so one could see by color which swapper AOE to walk into / visually distinguish multiple swappers by their rendered AOE color.

**Comment by SubordinalBlue** [comment]
Forgot the add the obvious… could also be useful for the player to visually distinguish other JDT block’s AOEs.

**Comment by Direwolf20-MC** [comment]
That would be cool :) I'll consider it as a future 'nice to have' feature!
