### ISSUE TITLE
Instant break RF cost calculation is incorrect with Efficiency

### ISSUE THREAD

**Issue by James103** [Direwolf20-MC/JustDireThings#143]
### Just Dire Things version

f8e0f95fefed48c165b238e5f244edb36a607251

### Minecraft Version

1.21

### Do you have optifine or Rubidium installed?

None

### Describe the issue

The Efficiency enchantment on the mod's tools can increase the RF cost of the instant break ability.

https://github.com/Direwolf20-MC/JustDireThings/blob/ae32e68d02f39646c52a7332b8c71629d49ff88c/src/main/java/com/direwolf20/justdirethings/common/items/interfaces/ToggleableTool.java#L206-L217
Currently, on inspection of the code in the function, it appears the calculation of the efficiency discount causes the energy cost to instantly decrease from (for example) 1,000 FE to 100 FE with Efficiency I, and further levels of Efficiency _multiply_ the cost by the Efficiency level instead of reducing it.
This is (a) way too OP in my opinion, (b) makes Efficiency **I** the best enchantment for the tool, and (c) nullifies the effect or even makes using the tool cost more if the Efficiency level is high enough, compared to without Efficiency.

Would it be possible to change the calculation so each level of Efficiency reduces the energy cost by 10% or multiplies it by 0.9, instead of the current formula?

### Steps to reproduce

1. Get a few max tier pickaxes from the mod and charge them up.
2. Apply and enable the instant break ability on each of them.
3. Label the first pickaxe A and don't apply any enchantments on it.
4. Label the second pickaxe B and apply only Efficiency I to it.
5. Label the third pickaxe C and apply only Efficiency V to it.
6. If possible, label the fourth pickaxe D and apply only Efficiency XX (20) to it.
7. Use all 3-4 pickaxes to mine one of the same block each using the instant break ability.
8. Compare how much energy was used by each of the four pickaxes.

### Expected behaviour

Efficiency should always reduce the RF cost to use Instant Break, not increase it.

**Comment by Direwolf20-MC** [comment]
You're absolutely correct! Thanks for the catch :).  This should now be resolved, see the attached commit for reference, and let me know if that looks good

**Comment by James103** [comment]
Your fix looks good.

You might want to return 0 as the `rfCost` if it would be negative, as mods like Apotheosis can allow Efficiency levels to exceed 10, which, with your fix, would make `rfCost` negative.
