### ISSUE TITLE
[Suggestion] Paradox copy fluid state

### ISSUE THREAD

**Issue by EpicCraft1997** [Direwolf20-MC/JustDireThings#147]
### Describe the feature you'd like to have added

It would also be amazing if it could copy the state of fluids, just imagine  the diiferent ways you could use that with like mekanism for example to automate stuff, of course time fluid would be blacklisted.

**Comment by Direwolf20-MC** [comment]
That’d be too powerful by default but you can add this yourself with block tags :)
