### ISSUE TITLE
Eclipse gate wand "eclipse gate" activation deletes iron doors.

### ISSUE THREAD

**Issue by tkuneck** [Direwolf20-MC/JustDireThings#150]
### Just Dire Things version

1.2.2

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.37

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Eclipse gate wand "eclipse gate" activation deletes iron doors.

### Steps to reproduce

0. Minecraft instance as described, only forge + jdt
1. new world, give necessary blocks + elipsegate wand.
2. construct a planks wall, 5 x 4, and put an iron door in the middle of it.
3. trigger eclipse gate in a 3x3x1 area that includes the iron door. planks + door phase out. I did set the range of the eclipse gate to 1 block deep.
4. observe only planks remain when blocks phase back in. Can walk right through where the door used to be.

### Expected behaviour

Iron door isn't deleted.

**Comment by Direwolf20-MC** [comment]
I think the best solution here is to just blacklist all doors :). This should be done in the next version of the mod. Note: If you eclipse gate the block under the door, just like with torches, the door will pop off as an item entity.
