### ISSUE TITLE
Productive bee entity not render when using Paradox machine 

### ISSUE THREAD

**Issue by iuhggiuhhgbnr** [Direwolf20-MC/JustDireThings#151]
### Just Dire Things version

1.2.1

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.34

### Modpack & Version

ATM10 0.46

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Use Paradox machine on Productive bee entity will result entity not render model + crash when try to breeding bee from Paradox machine

### Steps to reproduce

1. Get any bee from productive bee
2. Use Paradox machine to copy bee
3. Bee entity not render 

### Expected behaviour

Bee come out as normal like old mod version do

### Screenshots

![34w544vbnqmd1](https://github.com/user-attachments/assets/65cd9193-4521-47ae-a69d-bd715d9f1fe2)

### Log files

[crash-2024-09-06_22.38.05-client.txt](https://github.com/user-attachments/files/16910230/crash-2024-09-06_22.38.05-client.txt)

**Comment by Direwolf20-MC** [comment]
I don't think the crash is on my end.  I think this is just an example of an entity that won't work in the machine.  It should be added to the blacklist in the tags via the modpack :)
