### ISSUE TITLE
(Suggestion) Filters

### ISSUE THREAD

**Issue by Hamude99** [Direwolf20-MC/JustDireThings#153]
### Describe the feature you'd like to have added

Make some upgrades(like auto smelter) have a whitelist/blacklist filter or maybe even a tag filter in the settings menu

### Additional information

Would be really useful, since it's annoying to disable the upgrade every time you want to chop down trees, or for example in ATM10 having to disable it to get coal instead of graphite bars.

**Comment by Direwolf20-MC** [comment]
At this time I don't want to add this level of complexity, but I'll consider it :)
