### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by NyxaYu** [Direwolf20-MC/JustDireThings#156]
### Just Dire Things version

1.2.3

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.42

### Modpack & Version

ATM10 - 0.47

### Do you have optifine or Rubidium installed?

No

### Describe the issue

The console is being spammed

### Steps to reproduce

This line was probably included accidentally during testing.

https://github.com/Direwolf20-MC/JustDireThings/blob/c3a9ba71db83b3ad1f305911735031d33ddde97f/src/main/java/com/direwolf20/justdirethings/util/FakePlayerUtil.java#L175

### Expected behaviour

The console not to be spammed

### Screenshots

![image](https://github.com/user-attachments/assets/4d6ae74a-15b4-40dc-bf20-fb88eeabd70b)

### Log files

This is the result of a `System.out.println`, it does not show up in logs

**Comment by Direwolf20-MC** [comment]
You are correct! Thank you, this should be fixed in the next version
