### ISSUE TITLE
Mod interaction, Jump boost.

### ISSUE THREAD

**Issue by FangoDoggo** [Direwolf20-MC/JustDireThings#160]
### Just Dire Things version

1.3.0

### Minecraft Version

1.21.0

### (Neo)Forge Version

21.1.47

### Modpack & Version

ATM10 - 0.52

### Do you have optifine or Rubidium installed?

Yes

### Describe the issue

Jump boost breaking Elevators

### Steps to reproduce

1. Add jump boost too any Dire things boots.
2. Try use a elevator block upwards from Elevator Mod (1.21-1.10.1)
3. Elevator does not register jump for going up with jump boost on Just dire things boots enabled.
4. spam jump in despair.

### Expected behaviour

Jump too activate Elevator block, like usual and with all other jump boosts.

**Comment by Direwolf20-MC** [comment]
In testing, I find that holding the jump key does not activate the elevator, but tapping it does. Can you confirm?
