### ISSUE TITLE
Unrecoverable Every-Tick Crash: Fuel Canister with Sophisticated Backpacks' furnace addon

### ISSUE THREAD

**Issue by Evan109** [Direwolf20-MC/JustDireThings#161]
### Just Dire Things version

1.0.0

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.51

### Modpack & Version

Direwolf20 1.21 1.0.0

### Do you have optifine or Rubidium installed?

No

### Describe the issue

crash on the first tick after loading the world

### Steps to reproduce

Hard to say exactly what happened, here's my estimation
Make a backpack with a blast furnace addon, put a JDT fuel canister inside and smelt it.
Pick up a mob-dropped backpack and open it with the backpack hotkey
Internal Server Crash referencing the JDT fuel canister:
Description: Ticking entity
java.lang.RuntimeException: Invalid stack 1 justdirethings:fuel_canister for slot 1

### Expected behaviour

No crash

### Screenshots

World never loads, no screenshot.

### Log files

world file: https://drive.google.com/file/d/1FNUJja34p-K544JYWWmRE0m6J-p_VZdz/view?usp=drive_link
log file: https://drive.google.com/file/d/1oQZUxip5c2S08Rl8zUk8oPmcak0DaTQ9/view?usp=drive_link

### Additional information

It's late and i don't want to do more testing to figure out exactly how to reproduce, bug me tomorrow if more is needed and I'll update the description with more info. hopefully the world file and logfile is enough to make a start.

**Comment by Evan109** [comment]
I'll be trying to recover it using an external NBT editor when I get home from work to delete the fuel canister, hopefully that works.
Some clarifications:
I might have accidentally equipped the backpack, replacing my backpack with the running furnace using the fuel canister with the one I picked up. The furnace was being used at the time of the crash.
The backpack was at the Gold tier and had the crafting table, blast furnace, and anvil upgrades. The furnace was running smelting copper ore using the canister as fuel, but it had possibly finished.
The backpack on the ground was dropped by a zombie and appeared to have several items in it, i got one frame of it before crashing but i remember it looking like a dungeon chest, i know i saw C418-Cat before i crashed.
I had died and picked up my stuff using gravestones about a minute before the fatal encounter.

**Comment by Evan109** [comment]
I tried to remove the item via NBT editing but that didn't work. Removing the mod and loading the world however did.

**Comment by Direwolf20-MC** [comment]
Try as I might, I can't quite replicate this crash.  Can you repost the crash log somewhere that doesn't require a google sign in for me? :)

Also, if you can find any way to duplicate the crash that'd be helpful. 

![image](https://github.com/user-attachments/assets/db5962d4-12e4-4d69-abca-9ccd7a869615)

**Comment by Evan109** [comment]
My test procedures are slightly poorly worded.
In addition to this backpack (equipped in the relic/talisman/etc slots)
i picked up another backpack, hovered over it and pressed the backpack key to open that backpack
here is the log as a pastebin https://pastebin.com/PJgMgyah
if you have a suggestion as to how to give you the world file, that always instantly crashes when it's loaded, it may provide a more complete picture

**Comment by Direwolf20-MC** [comment]
Looking at the crash log I’m almost certain this is on sophisticated storage’s side. Can you open a report there? :)

**Comment by Evan109** [comment]
will do.

**Comment by Evan109** [comment]
Quote P3pp3rF1y of sophisticated storage:
"I fixed this issue a few days back the pack just needs to update sophisticatedcore to get the fix."

Been a while since i touched modded minecraft and im now a big fan of JDT. the progression feels good. Just finished upgrading to celestigem and am trying to find an ancient city without much success (yet)

**Comment by Direwolf20-MC** [comment]
Awesome thanks!! :)
