### ISSUE TITLE
JDT fuel canister CTD when placed inside Steve's Carts cart

### ISSUE THREAD

**Issue by Visandral** [Direwolf20-MC/JustDireThings#162]
### Just Dire Things version

1.4.0

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.51

### Modpack & Version

Direwolf20 - 1.21.1- 1.0.0

### Do you have optifine or Rubidium installed?

No

### Describe the issue

CTD and world corruption when putting a JDT fuel canister in a Steve's Carts cart

### Steps to reproduce

1. make Steve's Carts cart with a coal engine
2. put JDT fuel cell into the cart

### Expected behaviour

no crash

### Screenshots

can't get screenshot, world won't open

### Log files

world log from crash: https://paste.feed-the-beast.com/view/d4ee37d8
crash log: https://paste.feed-the-beast.com/view/208895f7
debug log seems to be too large for paste sites

### Additional information

Managed to decorrupt the world by loading it with Steve's Carts disabled, and the cart seemed to have mined a few blocks between inserting the fuel canister and CTD. Canister also worked with the cart assembler just fine.

**Comment by Direwolf20-MC** [comment]
This is almost certainly an issue on Steve’s carts side. I’ll sync up with them.

**Comment by Evan109** [comment]
Issue 161 may be related. The symptoms are the same, just interacting with a different mod

**Comment by Direwolf20-MC** [comment]
Agreed, that may be on Sophisticated Backpacks side, but I'll load them both in my dev environment to confirm :)

**Comment by gigabit101** [comment]
Fixed in 1.21-1.2.10

**Comment by Direwolf20-MC** [comment]
Thanks Giga!
