### ISSUE TITLE
Port for 1.20.1

### ISSUE THREAD

**Issue by ElNarco** [Direwolf20-MC/JustDireThings#163]
### Describe the feature you'd like to have added

Hey Dire,  long time fan and love your mods. I have recently got my 9yr old playing modded mc, he came from xbox mc, and he's having a blast.  I currently set us up a private server and run ur 1.20 pack. I'm taking him through and showing him how to work the mods and was wondering if Just Dire Things could be ported to that version.

**Comment by Direwolf20-MC** [comment]
I’m sorry but it would be a massive amount of work to back port it. Apologies!

**Comment by ElNarco** [comment]
Ok no problem. I'll get him through this pack and get him on your new one. Thanks for quick response. Keep up the good work
