### ISSUE TITLE
Liquid xp not asking experience tag

### ISSUE THREAD

**Issue by kts325** [Direwolf20-MC/JustDireThings#164]
### Just Dire Things version

1.4.0

### Minecraft Version

1.21.1

### (Neo)Forge Version

Current

### Modpack & Version

ATM 10 .53 Testing

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Liquid xp isn't tagged with experience tags like other mods are

### Steps to reproduce

Check tag
No xp tag

### Expected behaviour

Experience tag to allow unification between xp sources

**Comment by Direwolf20-MC** [comment]
Will add c:experience

**Comment by Direwolf20-MC** [comment]
Resolved :) thank you!
