### ISSUE TITLE
Step Assist Upgrade allows you sneak down a block

### ISSUE THREAD

**Issue by Rumobok** [Direwolf20-MC/JustDireThings#166]
### Just Dire Things version

1.4.0

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.51

### Modpack & Version

FTB Presents Direwolf20 1.21 (1.0)

### Do you have optifine or Rubidium installed?

No

### Describe the issue

With the Step Assist Upgrade installed the player is allowed to sneak down a block

### Steps to reproduce

1. Install Step Assist Upgrade and equip boots
2. Dig a block and place a bucket of lava into it
3. Try to sneak onto edge of block and you fall into lava (works without lava as well)
4. Burn to death

### Expected behaviour

You shouldn't be able to sneak down a block

### Additional information

I have only tested this with Ferricore Boots, however I am assuming that is applies to all of the boots with this upgrade installed.

**Comment by Direwolf20-MC** [comment]
Believe it or not - this is a vanilla issue.  

Mojang added the 'step height' modifier, and Neoforge uses their implementation of it. 

This isn't something I'll be able to solve (easily). Sorry!
