### ISSUE TITLE
Ore Miner misses deepslate 

### ISSUE THREAD

**Issue by satakrion** [Direwolf20-MC/JustDireThings#167]
### Just Dire Things version

1.4.0

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.51

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Ore Miner does not catch adjacent Ores when you either start mining stone or deepslate ore.

### Steps to reproduce

grap jdr-Pickaxe (ferricore is sufficient) with Ore Miner upgrade.
activate tool.
mine ore (ex. iron ore) adjacent to same ore in deepslate (ex. deepslate iron ore)
get iron drops from iron ore, but deepslate iron ore did not get touched.

### Expected behaviour

adjacent ore mined as well.

**Comment by Direwolf20-MC** [comment]
Unfortunately i don't think theres a good way to solve this one. The only other thing I could do is check if the adjacent block has the same tags, which will either cause iron to mine gold, or not work at all if the tags are slightly different.  

I think its just something we'll have to live with for now, sorry!
