### ISSUE TITLE
is there a way to disable the patchouli book from being added? 

### ISSUE THREAD

**Issue by VaporeonScripts** [Direwolf20-MC/JustDireThings#169]
### Describe the feature you'd like to have added

i dont want the patchouli book that is given when using this mod

### Additional information

a

**Comment by Direwolf20-MC** [comment]
Why? It doesn't automatically add it to your inventory or anything, its just a craftable book, and it only exists with Patchouli installed...

Is there a reason you don't want it there?

**Comment by VaporeonScripts** [comment]
Cuz it is given at every first join and it empty ,so it's useless

**Comment by Direwolf20-MC** [comment]
I’m not doing that with my mod. That’s sounds like a mod pack specific bug. What modpack are you using

**Comment by VaporeonScripts** [comment]
My own,ima look better where that book comes from

**Comment by Direwolf20-MC** [comment]
Sounds good. I don’t have anything in my mod that automatically gives you the book :)
