### ISSUE TITLE
XP Collector Totem

### ISSUE THREAD

**Issue by HeavyDeception** [Direwolf20-MC/JustDireThings#170]
### Describe the feature you'd like to have added

This may sound odd but would it be possible to have an item that links Experience Holder to each other?
 It would allow you to have multiple Holders but all linked to a single inventory that way you can have one at the front door one in the enchanting area that gives you Xp to level your items and one collecting Xp from your farms.
The dream would be that when you're enchanting it pulls the XP from it instead of you.

**Comment by Direwolf20-MC** [comment]
Since the exp holders are fluid containers, and you can pipe out XP fluid, you can already accomplish this by transfering the fluid from one enchanter to another :)
