### ISSUE TITLE
Duplication of weapon/tool upgrades with allays

### ISSUE THREAD

**Issue by FiXz1621** [Direwolf20-MC/JustDireThings#172]
### Just Dire Things version

1.4.1

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.57

### Modpack & Version

All the Mods 10 (0.55)

### Do you have optifine or Rubidium installed?

None

### Describe the issue

You are able to duplicate upgrades of the weapons/tools of the mod with allays

### Steps to reproduce

1. Have a tool with at least 1 upgrade installed.
2. Give tool to the allay mob.
3. Take the dropped upgrade and the tool from the allay.
4. The tool will still have the installed upgrade and now you have the dropped one too. 

### Expected behaviour

Either drop the upgrade and not have it on the tool or don't drop the upgrade but keep it on the tool

### Screenshots

Tool before the bug.
![Screenshot 2024-09-21 154731](https://github.com/user-attachments/assets/bae9bf8b-8014-42ed-bb3a-b0631719f261)
Giving allay the tool.
![Screenshot 2024-09-21 154741](https://github.com/user-attachments/assets/ce992302-2c9d-485c-9165-dae746afd47f)
Upgrade still in the tool and dupped upgrade.
![Screenshot 2024-09-21 154754](https://github.com/user-attachments/assets/fa7a5b14-851b-469e-820b-82023131c3df)

**Comment by Direwolf20-MC** [comment]
I'm almost certain this is a bug in Neoforge, because the event thats used to determine if an item was 'destroyed' is being called when you give an item to an allay - its totally out of my control and unfortunately not something I can resolve.  I'll check with the Neo team to see if i'm using the event incorrectly here, or if this is a bug on their side.

**Comment by FiXz1621** [comment]
> I'm almost certain this is a bug in Neoforge, because the event thats used to determine if an item was 'destroyed' is being called when you give an item to an allay - its totally out of my control and unfortunately not something I can resolve. I'll check with the Neo team to see if i'm using the event incorrectly here, or if this is a bug on their side.

Sweet! Thank you very much!
