### ISSUE TITLE
[Suggestion] Berry bushes being auto-harvastable by Blazebloom Soil

### ISSUE THREAD

**Issue by Zurkie** [Direwolf20-MC/JustDireThings#173]
### Describe the feature you'd like to have added

The Blazebloom Soil does not currently auto harvest berries grown on bushes - such as vanilla Minecraft's Sweet Berry Bushes, or Ars Nouveau's Sourceberry. Would be a welcome addition for automation.

**Comment by Evan109** [comment]
Piggybacking to ask for pumpkins/melons <3

**Comment by Direwolf20-MC** [comment]
Both have been added :)
