### ISSUE TITLE
Pickaxes missing tag cluster_max_harverstables

### ISSUE THREAD

**Issue by perlguy** [Direwolf20-MC/JustDireThings#174]
### Just Dire Things version

1.4.1

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.54

### Modpack & Version

Direwolf20 1.21 - 1.1.2

### Do you have optifine or Rubidium installed?

None

### Describe the issue

dire things pickaxes dropping fewer items from clusters (amethyst/geore/etc) than vanilla pickaxes due to missing tag cluster_max_harvestables (added in 1.21)

### Steps to reproduce

Use dire things pickaxe to mine amethyst or geore clusters.  Compare to mining same resource with vanilla pickaxes.

### Additional information

This is also happening with mining gadget lasers... but I'm kinda ok with that, as I can use the silk touch mod to collect the clusters, and then place and break with a pickaxe to get the drops.  But it was a bit surprising to get fewer drops with your laser+fortune 3, than with a vanilla diamond pickaxe.

Went looking at the GeOre source code and saw they use that tag to determine if it should drop full amounts (anything without that tag drops the same amount as if an explosion went off nearby).  That's why your tools aren't dropping "normal" amounts of drops from clusters.   Also - really enjoying your 1.21 pack.  Kudos to you and the FTB team.

**Comment by Direwolf20-MC** [comment]
Thanks for the report I’ll get it fixed in the next version :)

**Comment by perlguy** [comment]
Thanks!

On the off chance anyone else stumbles over this before the mods are updated, here's the kubejs I added to the pack (kubejs/server_scripts/dire_fixes.js) to fix it in the meantime.

```javascript
ServerEvents.tags("item", (event) => {
  event.add("minecraft:cluster_max_harvestables", [
    "justdirethings:ferricore_pickaxe",
    "justdirethings:blazegold_pickaxe",
    "justdirethings:celestigem_pickaxe",
    "justdirethings:eclipsealloy_pickaxe",
    "mininggadgets:mininggadget"
  ]);
});
```

**Comment by Direwolf20-MC** [comment]
This has been resolved and will be fixed in the next version :).  It will also be applied to the paxels. Thanks for the report, i had literally no idea this tag existed.
