### ISSUE TITLE
A Muffle Machine

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [Direwolf20-MC/JustDireThings#175]
### Describe the feature you'd like to have added

A machine that you can, just like others, define a box of specific proportions, then set any sound emitting block/entity within the bounds to either shut up completely, or decrease their volume.

Extra thing: maybe an option to INCREASE the volume too? I dont know of any uses for this part, thought I'd throw it out there though.

**Comment by Direwolf20-MC** [comment]
I think for now I’ll leave the muffling to one of the many sound muffler mods out there :). 

That said I may let you mute my machines some day but it’s a low priority. 

Thanks for the suggestion though!
