### ISSUE TITLE
[Suggestion] Fluid Fuel Canister

### ISSUE THREAD

**Issue by LeuckEfrain** [Direwolf20-MC/JustDireThings#177]
### Describe the feature you'd like to have added

Fuel canister that takes in any type of fluid that could be used to smelt items. Operates similarly to the fuel canister, just for fluids.

### Additional information

I noticed there is a fuel canister and a fluid canister, but not a fluid fuel canister. Since I have seen no one recommend this, I figured now would be as good a time as any.

**Comment by Direwolf20-MC** [comment]
Thanks, but I don't think I'll be adding this one
