### ISSUE TITLE
[BUG] Jumbo furnace doesnt keep fuel canister in the fuel slots

### ISSUE THREAD

**Issue by BamsTheSergal** [Direwolf20-MC/JustDireThings#178]
### Just Dire Things version

1.4.1

### Minecraft Version

1.21

### (Neo)Forge Version

21.1.58

### Do you have optifine or Rubidium installed?

Yes

### Describe the issue

Jumbo furnace mod doesnt keep fuel canister in the fuel slots

### Steps to reproduce

1. open the jumbo furnace
2. put fuel canister in fuel slot
3. smelt something in the furnace
4. watch as fuel canister moves to output in jumbo furnace

### Expected behaviour

to stay put in fuel slot

### Screenshots

[javaw_AcLIGQDhVE.webm](https://github.com/user-attachments/assets/5bdfeeba-788c-4789-afda-bb5a86d6b4b9)

### Log files

none sadly as this isnt a crash

### Additional information

it seems to work only once, then instantly puts it in the fuel slot, like in the video.

**Comment by BamsTheSergal** [comment]
i cross posted this in [jumbo furnace #26](https://github.com/Commoble/jumbo-furnace/issues/26)

**Comment by Direwolf20-MC** [comment]
This is almost certainately something that needs to be fixed on their side :). Sorry!  Feel free to reopen if they say otherwise

**Comment by BamsTheSergal** [comment]
o7, i am sorta new to how github and this stuff works, but loving the mod so far!
