### ISSUE TITLE
Upgrade dupe with gravestone mod

### ISSUE THREAD

**Issue by yi-fan-song** [Direwolf20-MC/JustDireThings#179]
### Just Dire Things version

1.4.1

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.54

### Modpack & Version

Direwolf20 - 1.21 1.1.2

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Any upgrade can be duped when breaking a gravestone while holding a just dire things upgradable item

### Steps to reproduce

1. Die with hotbar slot 1 filled with dirt to spawn a gravestone
2. Respawn and put any upgradable item on hotbar slot 1
3. Break the gravestone with hotbar slot 1 selected
4. When broken, any upgrade the item had will be dropped on the ground

### Expected behaviour

Upgrades do not drop on the ground

### Additional information

I tried the same steps but using an armor slot, but it did not drop the upgrades.

When gravestone mod is moving items away to put the hotbar from the gravestone back, it seems to trigger the check for items breaking (but this works with any item tier), thus dropping upgrades when it shouldn't.

**Comment by yi-fan-song** [comment]
ok so I looked into the code, and my best bet is that gravestone triggers on the same tick and since [here](https://github.com/Direwolf20-MC/JustDireThings/blob/main/src/main/java/com/direwolf20/justdirethings/common/items/interfaces/Helpers.java#L173)
`hurtAndBreak` is called before checking if the item was broken in the process so since gravestone moves the item (it somehow doesn't place the old items in the same tick), the slot is now empty and now the code thinks the item had been broken.

Ideally if there was a hook for onItemDamage or something similar, I'm not a mod developer so I have no knowledge about this. I'd have to dig into neoforge/minecraft code/docs.

Another option is to split the damaging the item and the left click, essentially this is already what minecraft code does, I'm not sure if the API is public, in [neoforge](https://github.com/neoforged/NeoForge/blob/762725e95def8b5bb1bf168a4ead233d7e0f686e/patches/net/minecraft/world/item/ItemStack.java.patch#L118), there seems to be a patch on the call to `damageItem`, so maybe this could be used.

**Comment by Direwolf20-MC** [comment]
I checked and I am almost positive this is a bug on Gravestone's side.  The event is being fired by vanilla (well Neoforge), not by my implementation of it. Can you please open a report on Gravestone's github, and let them know that if they believe its actually on my side to contact me?

![image](https://github.com/user-attachments/assets/7657b175-29ab-4a96-840d-684e367d7421)

**Comment by yi-fan-song** [comment]
I thought that line fired the event 😅, apologies
