### ISSUE TITLE
Allow the click to work with mending enchant?

### ISSUE THREAD

**Issue by HeavyDeception** [Direwolf20-MC/JustDireThings#182]
### Describe the feature you'd like to have added

Allow tools with mending inside the clicker to be repaired when Xp is outside the block or piped in from a source.

### Additional information

It would be nice if both versions could do this but I could see the advanced only having this with it being able to hold liquid.

**Comment by Direwolf20-MC** [comment]
That would be super nice, but a lot of effort to do, especially with how rarely i think people would use this feature.  I think for now the best thing to do is use tier 3 tools in advanced blocks.  They automatically charge them :).  Sorry, i'm going to have to pass on this request. At least for now.
