### ISSUE TITLE
Using Eclipse Gate destroys Powah Player Transmitter, it does not get restored. It does drop the card though.

### ISSUE THREAD

**Issue by Slugstur** [Direwolf20-MC/JustDireThings#184]
### Just Dire Things version

1.4.1

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.58

### Modpack & Version

Craftoria 1.3.2

### Do you have optifine or Rubidium installed?

None

### Describe the issue

If you use eclipse gate on an area that includes a player transmitter from Powah it does not get restored.

### Steps to reproduce

1. Place a few block to use the eclipse gate on
2. Put a player transmitter behind it
3. Use eclipse gate
4. Wait for the blocks to be restored
5. Cry because you lost your nitro transmitter

### Expected behaviour

The transmitter being restored

**Comment by Direwolf20-MC** [comment]
I'll check into this -- it doesn't make any sense though, because I assume the player transmitter is a block entity, and those are explicitly blocked from being gated! :)

I'll test in dev, and see whats up

**Comment by Direwolf20-MC** [comment]
So it turns out that the Player transmitter is two blocks (Like a door) and only one of them has a block entity on it. I'll have to figure out a fix for this....

**Comment by Direwolf20-MC** [comment]
Ok got it fix - i just added these blocks to the deny list for the wand, thanks for the report!

**Comment by Slugstur** [comment]
Thanks for fixing it!
