### ISSUE TITLE
Just Dire Things soils fully break Farmer's Delight tomato plants

### ISSUE THREAD

**Issue by zevaryx** [Direwolf20-MC/JustDireThings#185]
### Just Dire Things version

1.4.1

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.54

### Modpack & Version

Direwolf20 - 1.21 (1.1.2)

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Farmer's Delight tomato plants have 2 stages of growth, budding tomato vine and tomato vine. The various soils (I have Blazebloom soil) fully breaks the tomato vine back into a budding tomato vine. Right clicking on the tomato vine only harvests the tomatoes and does not revert the plant back to a budding tomato vine.

### Steps to reproduce

1. Till soil with any Just Dire Things hoe
2. Plant a Farmer's Delight tomato plant
3. Wait for the plant to fully grow and be harvested

### Expected behaviour

The tomatoes to be harvested and the plant to still be in the full tomato vine growing phase

**Comment by Direwolf20-MC** [comment]
I'm gonna have to come up with a solution for this, because I can't "Special Case" every plant of this type :).

**Comment by zevaryx** [comment]
Going through all of the crops in the 1.21 pack (that can grow on the soils at least), the only other bugged seed is rice, which requires it to be in water (which may be the issue). The rice doesn't get harvested at full maturity

**Comment by Hexblood** [comment]
I would like to add that at least the Blazebloom Soil is not growth accelerating the Tomato Plant from Farmer's Delight. I have not tested other soils yet.

**Comment by Direwolf20-MC** [comment]
I've made changes to the soils - can you let me know if this solved most of your issues in the next version?
