### ISSUE TITLE
6 option for the block placer and breaker?

### ISSUE THREAD

**Issue by HeavyDeception** [Direwolf20-MC/JustDireThings#186]
### Describe the feature you'd like to have added

An all-sides option would help automate blocks like Certus quarts and other modded blocks including the Goos.

**Comment by Direwolf20-MC** [comment]
I'm not sure you understand what the direction button does - it doesn't specify which blocks can be broken, it specifies which direction the breaking occurs from :).  If you want to automate certus/goos use the Advanced block breaker.
