### ISSUE TITLE
Paxel not keeping upgrades when crafting.

### ISSUE THREAD

**Issue by HeavyDeception** [Direwolf20-MC/JustDireThings#187]
### Just Dire Things version

19.18.10.218

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.61

### Modpack & Version

ATM 10-0.57

### Do you have optifine or Rubidium installed?

I have other rendering based mods installed

### Describe the issue

When crafting the Paxel any upgrades are lost if it is not on the axe.

### Steps to reproduce

1. Make the Celestigem Pickaxe, Axe, Shovel
2. Add Upgrades
3. Try to make the paxel.

### Expected behaviour

For the Paxel to have the upgrades or for them to drop.

### Screenshots

https://i.imgur.com/z1lGAIM.gif  You can download the gif if it doesn't play it's just showing what's happening.

### Log files

N/A

### Additional information

It seems that it only uses the Axes info to get upgrades for the paxel.

**Comment by LezChap** [comment]
Enchants are also lost.

**Comment by Direwolf20-MC** [comment]
I haven't been able to duplicate the issue of upgrades not working - but i DID fix the enchantments issue :)
