### ISSUE TITLE
Tiered Charcoal?

### ISSUE THREAD

**Issue by LezChap** [Direwolf20-MC/JustDireThings#188]
### Describe the feature you'd like to have added

I suggest adding the ability to make Tiered Charcoal like you can the Tiered Coal.  

To balance it (because how easy it is to farm charcoal with a tree farm) I suggest either just having it increase the burn speed modifier without the additional time modifier for the tier, or possibly to reduce the burn speed modifier (by 0.5 per tier?) as well.  

This would make tree/charcoal farms somewhat more viable/reasonable again when you get into the "late game" of JustDireThings.

**Comment by Direwolf20-MC** [comment]
I've been toying with how to do this. On one hand I'd like to add a charcoal block.  On the other, lots of other mods already do :). 

Its on my todo list to figure this out. Thanks for the suggestion! Going to close the issue for now, but just know I'm working on *something* to do this :).
