### ISSUE TITLE
[Suggestion] A dummy item to link ability 

### ISSUE THREAD

**Issue by pwaksman973** [Direwolf20-MC/JustDireThings#189]
### Describe the feature you'd like to have added

So we have all those abilities that we can bind to a hotkey, but that is a lot of hotkeys.
Very easy to lose track of and very had to check again what is what. I mean not hard in terms of complexty, but annoyingly enough to make a pain.

Would be super helpful if we had the possibility to also link the skill activation to a dummy item, and we would just have the normal left/right click options as we have for the tools skill.

### Additional information

For example, you want to have invurnerability from the armor and decoy. So instead of bound to hotkey X and hotkey Y, 
you could bound to the dummy item, the dummy item would be just a normal item stakc that can go in any slot bar 1, 2, 3 ... 0.
And then you also choose which skill goes in which button (left/right).

That would be much more manageable then keeping track of a buch of hotkeys.
Hotkey system is super cool, but too many keys become a pain. Not even considering all the other mods hotkeys.

So back to the sample, invurnerability  + decoy, would bound to a dummy item, then place it in the hotbar, and have left click for decoy, and right click for invurnerability. 

And then maybe bind more then one skill on each dummy item depending on the item level, like ferricore bind only one skill on each left or right click, blazegold 2, yata, yatta.

**Comment by Direwolf20-MC** [comment]
No sorry, I don't think this is a viable option.
