### ISSUE TITLE
Seed Dupe

### ISSUE THREAD

**Issue by HeavyDeception** [Direwolf20-MC/JustDireThings#190]
### Just Dire Things version

1.4.2

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.61

### Modpack & Version

ATM 10-0.58

### Do you have optifine or Rubidium installed?

I have other rendering based mods installed

### Describe the issue

The Hose with hammer installed with dupe seeds.

### Steps to reproduce

1. Make An Eclipse Alloy Hoe
2. Add hammer
3. have 1 seed in the hot bar (aka Mystical Agriculture)
4. Right-click with a hoe and it will auto-plant with the seeds in the hot bar.

### Expected behaviour

Tile all selected ground and plat one seed.

### Additional information

Looking to see what mod adds the right click and plant function.

**Comment by Direwolf20-MC** [comment]
I'm almost certain I didn't set my hoes up to auto-plant seeds for you :).  I assume this is another mod doing this, and its likely a bug on their side, not expecting my hoe to do this.
