### ISSUE TITLE
Hammer Toggle - Ability Enabled Text

### ISSUE THREAD

**Issue by LezChap** [Direwolf20-MC/JustDireThings#192]
### Describe the feature you'd like to have added

Add the hammer size when using the keybind to the text on screen.

Currently is just says "Ability: Hammer - Enabled" or "Ability: Hammer - Disabled" when toggling through the Hammer sizes. Adding "Hammer 3x3/5x5/7x7 - Enabled" would give players another indicator (other than the block outline overlay) for the currently set hammer size and prevent possibly mining more than is intended.

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo
Pass: changeme

you may need to install the c compiler

**Comment by LezChap** [comment]
https://github.com/Direwolf20-MC/JustDireThings/pull/219 Beleive this commit you just made resolves this request.
