### ISSUE TITLE
middle tier machines

### ISSUE THREAD

**Issue by ErikHaag** [Direwolf20-MC/JustDireThings#195]
### Describe the feature you'd like to have added

JDT has simple machines that work on a single block in front of themselves and advance machines that work on volumes.
I think it would be nice to have a "sophisticated" tier that still work on 1 block, but can be disjoint from the machine
for most machines, the sophisticated tier would require blazegold, while the swapper would require celestigems.
the machines should use power, though maybe less than their advance counterparts.

**Comment by Direwolf20-MC** [comment]
Sorry thats a whole lotta work :).  I think the way the current machines are is fine.
