### ISSUE TITLE
Teleport binding for tier 3 items

### ISSUE THREAD

**Issue by ThepikaMan** [Direwolf20-MC/JustDireThings#196]
### Describe the feature you'd like to have added

I'd love an indicator for binded blocks aswell as a way to see if I've done the bind correctly. the cordinate system is a good placeholder but it's abit unintuitive. Love the mod though great job for the most part ^^

**Comment by LezChap** [comment]
I'd love if, while holding a tool with Teleport, if you're within 16 blocks of your bounded block, that block is highlighted or brightly outlined.

**Comment by ThepikaMan** [comment]
> I'd love if, while holding a tool with Teleport, if you're within 16 blocks of your bounded block, that block is highlighted or brightly outlined.

I like that Idea but I'd like an option to render it and also turn it off just like most machines in the mod :v

**Comment by Direwolf20-MC** [comment]
Render Added - along with a toggle on the ability to hide it :)
