### ISSUE TITLE
Railcraft Blast Furnace eats fuel canister

### ISSUE THREAD

**Issue by dcaster19** [Direwolf20-MC/JustDireThings#197]
### Just Dire Things version

1.4.2

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.61

### Modpack & Version

Direwolf20 1.21-1.2.1

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Railcraft Blast Furnace uses up fuel canister

### Steps to reproduce

1. Open Direwolf20 pack. 
2. Craft or obtain fuel cannister from Just Dire Things 
3. Load fuel into canister. 
4. Form Railcraft blast furnace mutiblock 
5. Load Railcraft Blast Furnace with iron ingots and fuel cannister. 

Result: Railcraft Blast Furnace uses up fuel cannister as a piece of coal destroying the item and not using the burn time

### Expected behaviour

Blast Furnace uses fuel canister burn time instead of using up fuel cannister

**Comment by Direwolf20-MC** [comment]
This is a bug on railcrafts side ;). Please let them know the furnace needs to return items like a bucket when using lava.
