### ISSUE TITLE
Duplication bug - place tool / armor in item frame drops copy of upgrades

### ISSUE THREAD

**Issue by TOLoneWolf** [Direwolf20-MC/JustDireThings#198]
### Just Dire Things version

1.4.2

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.61

### Modpack & Version

FTB Presents Direwolf20 1.21 version 1.2.1

### Do you have optifine or Rubidium installed?

I have other rendering based mods installed

### Describe the issue

Dupe Upgrades on items

### Steps to reproduce

1. Install upgrade on tool/armor.
2. place tool/armor in an item frame.
3. upgrades drop on the ground and stay installed in the tool/armor.

**Comment by Direwolf20-MC** [comment]
This bug is actually on the neoforge side of things. I won’t be able to do much :(
