### ISSUE TITLE
Pumpkin Head Upgrade - Prevent Endermen Aggro

### ISSUE THREAD

**Issue by LezChap** [Direwolf20-MC/JustDireThings#200]
### Describe the feature you'd like to have added

Have a helmet upgrade that prevents Endermen from getting angry when you look at them, similar to the effect of wearing a carved pumpkin.  Not sure which tier this fits best on, I'll leave it up to you.

**Comment by Direwolf20-MC** [comment]
I think I'll hold off on this - I think the balance of vanilla is that you give up armor protection to get the pumpkin head :)
