### ISSUE TITLE
Soils with Teleport don't catch Poisoned Potatoes

### ISSUE THREAD

**Issue by LezChap** [Direwolf20-MC/JustDireThings#202]
### Just Dire Things version

1.4.2

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.61

### Modpack & Version

Direwolf20 1.21 (1.2.1)

### Do you have optifine or Rubidium installed?

None

### Describe the issue

The Tier 3/4 soils which teleport crop products to an inventory do not teleport Poisoned Potatoes (from the Potato crop).  The Poisoned Potatos end up dropped in the world.

### Steps to reproduce

Plant Potato
Wait for RNG for a Poisoned Potato.

### Expected behaviour

The poisoned potato should end up in the inventory with the rest of the potatoes that are harvested.

**Comment by ThepikaMan** [comment]
I have successfully made it pick up poisoned potatoes. It's just that it doesn't tell you that you have to bind each tilled soil individually, if not bound correctly.

**Comment by LezChap** [comment]
@ThepikaMan Are you saying you have to re-bind the hoe to the inventory before tilling each block of farmland to get it to work for the poison potatoes, even tho the teleport works with the normal potatoes without doing so?

**Comment by ThepikaMan** [comment]
> @ThepikaMan Are you saying you have to re-bind the hoe to the inventory before tilling each block of farmland to get it to work for the poison potatoes, even tho the teleport works with the normal potatoes without doing so?

Well it seems to be that way for it to pick anything up at all if not bound to an inventory before tilling the ground you want items to teleport from. I thought it was gonna be a passive thing it just did, if you had an inventory bound. But apparantly you have to make sure before hand :y

**Comment by LezChap** [comment]
I think the farmland is bound fine.  I bound my inventory with the Hoe, ran to the farm, and tilled a 9x9 farm.  All the primary products are harvesting without issue.  Potatoes are harvesting and going into my inventory fine.  It's just the poisoned potatoes I've been having an issue with.

**Comment by Direwolf20-MC** [comment]
Just tested in my dev env - poison potatoes are definitely showing up in the chest :).  Are you maybe bound to a drawer or something that doesn't accept poison potatoes?
