### ISSUE TITLE
CTD Ticking block entity

### ISSUE THREAD

**Issue by kalutro** [Direwolf20-MC/JustDireThings#204]
### Just Dire Things version

0.9.12

### Minecraft Version

1.20.4

### (Neo)Forge Version

20.4.237

### Modpack & Version

FTB NeoTech 1.7.0

### Do you have optifine or Rubidium installed?

No

### Describe the issue

CTD when changing desired area on Block Breaker.

### Steps to reproduce

Was changing the desired area on the Block Breaker when this occured. Breaker was running, had show area on, and was equipped with a Celestigem Axe. I was changing the Y-coord. The Axe had Tree Feller, Auto Smelter, and Drops Teleporter on.

No problems when loading the game back up.
Log: [crash-2024-10-03_14.57.32-server.txt](https://github.com/user-attachments/files/17250663/crash-2024-10-03_14.57.32-server.txt)

### Expected behaviour

Expected not to crash. :)

**Comment by Direwolf20-MC** [comment]
Sorry that version is no longer supported, please let me know if this happens in 1.21+
