### ISSUE TITLE
Block Breaker Breaking Block Breaker Crash

### ISSUE THREAD

**Issue by Nyxane** [Direwolf20-MC/JustDireThings#205]
### Just Dire Things version

1.4.2

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.62

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Placing a Block Breaker in the working area of a Block Breaker causes a crash

### Steps to reproduce

- Place down a block breaker
- Place a pick that is able to mine Block Breakers in the placed Block Breaker
- Place down another Block Breaker in the working area

### Expected behaviour

For it to not crash and drop the new block breaker including its items if it has any

### Log files

https://mclo.gs/Zj6aZ33

**Comment by Direwolf20-MC** [comment]
Thanks for the report - this will be fixed in the next version!
