### ISSUE TITLE
Ticking entity crash with JDT Clicker when a Sunrise Glyph from Ars Nouveau is inserted

### ISSUE THREAD

**Issue by SubordinalBlue** [Direwolf20-MC/JustDireThings#206]
### Just Dire Things version

1.4.2

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.59

### Modpack & Version

Craftoria 1.4.1

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Just as the title says

### Steps to reproduce

I'm passing this along from a user report on AOE discord

### Expected behaviour

Not crashing ^^

### Log files

https://pastebin.com/a2YeLt5U

**Comment by SubordinalBlue** [comment]
Not even sure it's JDT's "fault", but came here first as it is the clicker that the crash report pins the finger on.

**Comment by Direwolf20-MC** [comment]
Thanks for the report :) this appears to be more on Ars’s side. Can you open a report there? :)

**Comment by SubordinalBlue** [comment]
TY for taking a look at it; will share it with Ars next.

p.s. Still loving the mod... a big TY for it. Very much looking forward for enough personal play time to explore the newer parts myself.
