### ISSUE TITLE
Auto fire Upgrade for bow

### ISSUE THREAD

**Issue by zanderkent** [Direwolf20-MC/JustDireThings#207]
### Describe the feature you'd like to have added

Adding an auto fire upgrade to Celestigem and higher would be awesome! 

### Additional information
This mechanic would be similar to how draconic evolution’s auto fire upgrade worked. Where as soon as it was pulled back all the way it would fire the arrow.
_No response_

**Comment by Direwolf20-MC** [comment]
I never really liked that mechanic :) I think i'll pass - thanks for the suggestion though!
