### ISSUE TITLE
making shaders work on the goos

### ISSUE THREAD

**Issue by PookiSlayer172** [Direwolf20-MC/JustDireThings#209]
### Describe the feature you'd like to have added

just making shaders work with goos, as of the latest version of your new ftb modpack, shaders dont work with any of the goos. the only option for shaders is iris right now but it suck not having it look pretty and see oh i have about this much time left before the goo is done doing its thing.

### Additional information

its not crazy important, but it would be good QOL thing to do. i was using complimentary reimaged just incase thats important to note. have a good dayyyy

**Comment by Direwolf20-MC** [comment]
I have no idea how to do this, sorry!
