### ISSUE TITLE
Void Shift renders when in off hand even when set to hide render

### ISSUE THREAD

**Issue by zperk13** [Direwolf20-MC/JustDireThings#210]
### Just Dire Things version

1.4.2

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.61

### Modpack & Version

ftb-presents-direwolf20-11 - 1.2.1

### Do you have optifine or Rubidium installed?

No

### Describe the issue

A voidshift wand, when the voidshift setting is set to hide render, while it does hide the render when the wand is in the main hand, it does not hide the render while in the off hand

### Steps to reproduce

1. Hold Voidshift wand in main hand
2. Shift-RightClick to open wand settings
3. Right click on "Void Shift"
4. Set the "Show Render" setting to be "Hide Render"
5. Swap wand to offhand

### Expected behaviour

Player render should be hidden when the setting in hidden not only when the wand is in your main hand, but also when it's in the offhand

### Screenshots

![2024-10-07_15 07 54](https://github.com/user-attachments/assets/5da94e07-3119-4d3b-b837-0cfcc419eb82)
![2024-10-07_15 07 56](https://github.com/user-attachments/assets/9489aa46-3853-47b4-81a8-68417e6ccc16)

**Comment by Direwolf20-MC** [comment]
Will be fixed in the next version, thanks!

**Comment by zperk13** [comment]
That was... incredible timing... I thought "I've fixed bugs in Minecraft mods before, might as well take a crack at it", you committed that as I was looking through the code. I found the line of code you did and thought "This should be working, hmm, maybe someone fixed it". Checked the blame and you did, 3 minutes earlier!
