### ISSUE TITLE
Wrench "Bound to" cannot be cleared

### ISSUE THREAD

**Issue by FaintSpeaker** [Direwolf20-MC/JustDireThings#211]
### Just Dire Things version

1.4.2

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.61

### Modpack & Version

FTB Presents Direwolf20 1.21 v 1.2.1

### Do you have optifine or Rubidium installed?

I have other rendering based mods installed

### Describe the issue

Wrench does not clear if block is broken before completing binding.

### Steps to reproduce

1. Place 2 Simple Swappers
2. Start binding on one of the swappers
4. Verify that the wrench now is in "Bound to:" state
5. Remove the swapper you just bound to
6. Place the swapper someplace else
7. Observe that you can no longer use the wrench to bind any blocks.

### Expected behaviour

Wrench should recognize that the location is no longer valid, OR, allow me to clear it (either by crafting it by itself, like the machines) or shift right-clicking air.

### Additional information

If you place the swapper back in the original place (The coordinates in the wrench's tooltip) you can click it again to "remove binding" and the wrench works perfectly normal.

I am using Iris Shaders.

**Comment by Direwolf20-MC** [comment]
Resolved - thank you!
