### ISSUE TITLE
[Request] Tick Accelerator Block

### ISSUE THREAD

**Issue by DizzyDJW** [Direwolf20-MC/JustDireThings#212]
### Describe the feature you'd like to have added

I have an idea for a more permanent tick acceleration method.

Use a creature catcher on a Paradox and get a Captured Singularity back.

Combine that captured singularity with some time crystals and then drop the resulting Unrealized Singularity into some time fluid and get a Realized Singularity back.

Once placed it becomes an Inactive Time Dilator, and when filled with Time Fluid, it can tick accelerate blocks in an area of your choosing, at the speed set inside the block's settings, for the cost of time fluid.

Time Fluid cost is determined by either the larger the area, regardless of the number of tick accelerated blocks, the higher the cost in time fluid, or the opposite, the area can be whatever and the number of blocks affected determines the cost of time fluid for it to run, while obviously, the higher the tick acceleration setting the more time fluid used.

Also, PLEASE make AE2's Growth Accelerator work on Time Crystals, they're too slow, and cannot be tick accelerated. Granted, they're easy to automate.

### Additional information

I feel this is very balanced, as:
1) You must already have access to the Paradox Machine AND enough Time Fluid to generate a Paradox. (High cost, late game)
2) It runs on Time Fluid much like the wand. (Not infinite or only power which is too easy to get)
3) It could also generate Paradox Energy, but instead of creating a new paradox, the machine must be fed a Time Crystal occasionally to bring the Paradox Energy back down.

**Comment by Direwolf20-MC** [comment]
Also Time wand works on my crystals, and I would expect AE2 growth thing to work on them too, but I haven't tried it.

**Comment by DizzyDJW** [comment]
> Also Time wand works on my crystals, and I would expect AE2 growth thing to work on them too, but I haven't tried it.

From my testing neither the wand nor the AE2 Growth accelerator make any difference, I timed it, automated for a few hours, one with 2 growth things on each crystal and one without and there was no increase in time crystal growth speed. Also I applied the full 256x speed with the wand to the Budding Time Crystal blocks and also no noticeable increase in speed.

**Comment by Direwolf20-MC** [comment]
I’ll test :) but in my dev env they definitely worked last time I checked.
