### ISSUE TITLE
The new Charcoal Block is not breakable by any tools

### ISSUE THREAD

**Issue by Zurkie** [Direwolf20-MC/JustDireThings#214]
### Just Dire Things version

1.4.3

### Minecraft Version

1.21.1

### Do you have optifine or Rubidium installed?

None

### Describe the issue

The newly added Charcoal Block is not breakable by any tools

### Steps to reproduce

1. craft Charcoal Block
2. place it on the ground
3. try to hit it with pickaxe (tried celestigem and iron pickaxes)
4. block doesn't break

**Comment by Direwolf20-MC** [comment]
Woops! Will release a hotfix
