### ISSUE TITLE
Hammer Mode Tooltip

### ISSUE THREAD

**Issue by KyBeeS** [Direwolf20-MC/JustDireThings#218]
### Describe the feature you'd like to have added

Add a 3x3, 5x5 ,7x7 tooltip when switching hammer mode instead of the pop-up that just says "hammer enabled" you could change it to the aforementioned levels so you have a popup saying what size you're on without looking at a block

**Comment by zperk13** [comment]
I was thinking the same thing! I was bored so I went ahead and coded it and made a PR

**Comment by Direwolf20-MC** [comment]
PR Accepted - thank you!
