### ISSUE TITLE
Machines don't reset their working area when rotated.

### ISSUE THREAD

**Issue by anexusarchon** [Direwolf20-MC/JustDireThings#22]
If you place a simple block breaker or placer, and then rotate it with the wrench, the block breaker or placer will still try to break or place blocks at the original front regardless of new orientation.

**Comment by Direwolf20-MC** [comment]
Thanks for the report, just resolved it, and will be fixed in the next version :)

**Comment by anexusarchon** [comment]
Awesome , thanks
