### ISSUE TITLE
keybind to access config screen

### ISSUE THREAD

**Issue by antisocialian** [Direwolf20-MC/JustDireThings#220]
### Describe the feature you'd like to have added

I think a keybind to access the config screen would help since the only way to access armor config that i can find is to access the tool config and right click the armor in that screen.

**Comment by Direwolf20-MC** [comment]
Added with - https://github.com/Direwolf20-MC/JustDireThings/commit/d695f8e4586a669935cc188fcde864c4208b3b99

Thanks!
