### ISSUE TITLE
Creature Catcher Items Frame Render

### ISSUE THREAD

**Issue by ChosenArchitect** [Direwolf20-MC/JustDireThings#221]
### Just Dire Things version

1.4.4

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.66

### Do you have optifine or Rubidium installed?

Yes

### Describe the issue

Creature Catcher Doesn't render correctly inside of the an item frame

### Steps to reproduce

1. Catch mob with catcher
2. Place catcher inside of an Item frame
3.  See mob display out of place. (would also be nice if the catcher was laying on its base flat for decoration)

### Expected behaviour

Expect it to respect the position of the item frame and lay flat for a display and this also includes the mob render as well.

### Screenshots

![image](https://github.com/user-attachments/assets/c88d57e6-fac5-4935-88a5-2fb47f0a6791)

**Comment by Direwolf20-MC** [comment]
Resolved in next version - thanks chosen :)

**Comment by ChosenArchitect** [comment]
No prob :D
