### ISSUE TITLE
Make chunkloading optional

### ISSUE THREAD

**Issue by phit** [Direwolf20-MC/JustDireThings#222]
### Describe the feature you'd like to have added

Add a setting to disable chunkloading for portals, especially on servers this is a big issue, not sure why they need chunkloading at all?

### Additional information

Chunkloading was added with https://github.com/Direwolf20-MC/JustDireThings/commit/a2a55f43ac904cd6d3d7ac191988c455b465ea8c and there's no way to disable it

**Comment by Direwolf20-MC** [comment]
My experience with the portals was that if the area wasn't chunkloaded they didn't work. So i had to add chunk loading to make sure they did.

**Comment by phit** [comment]
I mean that's not really a good reason? Any other modded portal at least that I've ran into in ATM10  is happy without adding chunk loading tickets. I'm happy to investigate why you had this experience, the performance hit of players being able to spawn permanent chunk loaders without any control as a server admin would otherwise force me to disable the portal gun outright.

**Comment by Direwolf20-MC** [comment]
I'll investigate a way to avoid having it - the problem is because the portals link to each other by looking up the portal entity, i'd have to re-write the entire mechanic of how the portals work if i wanted to avoid chunk loading them. 

I'll consider this :)
