### ISSUE TITLE
Source Berry Bushes do not auto harvest on BlazeBloom Soil

### ISSUE THREAD

**Issue by Rafiki2085** [Direwolf20-MC/JustDireThings#224]
### Just Dire Things version

1.4.2

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.61

### Modpack & Version

Direwolf20 1.21 version 1.2.1

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Sourceberry Bushes on Blazebloom soil do not get harvested

### Steps to reproduce

1. Create BlazeBloom Soil
2. Plant Sourceberry
3. Never gets harvested automatically

Note: It would be great if this also worked on Pumpkin and Mellon Steams as well.

### Expected behaviour

Should be auto harvested like other crops

**Comment by Direwolf20-MC** [comment]
Should be resolved by: https://github.com/Direwolf20-MC/JustDireThings/commit/08aceef72e41019e9d24127f96f1be49d8a50192

Thanks!
