### ISSUE TITLE
[Request] Beheading Module

### ISSUE THREAD

**Issue by DizzyDJW** [Direwolf20-MC/JustDireThings#225]
### Describe the feature you'd like to have added

Self-explanatory. Not many mods handle Beheading anymore, or are difficult to find, I recently suggested adding Mob Grinding Utils strictly for lack of Beheading, but giving us a module for our sword/axe too? might help a lot, especially since most players will be using your Clicker and swords to make a mob farm anyway. 

I suggest making it so that the module can be either upgraded to higher levels of Beheading just with weapon tiers or better yet both that and the ability to enchant the module with Efficiency or Sharpness first before adding it gives us higher levels of Beheading, in case for some reason a person enjoys Blazegold or Celestagem tier more than the Eclipse Alloy tier, for looks, or if Eclipse Alloy tier is limited to Beheading III, but Apotheosis allows for your module to reach Beheading X.

**Comment by Direwolf20-MC** [comment]
I think I'll leave this one off for now, but thanks for the suggestion!
