### ISSUE TITLE
Block breaker not consuming FE on Mekanism Atomic Disassembler

### ISSUE THREAD

**Issue by Gaz492** [Direwolf20-MC/JustDireThings#227]
### Just Dire Things version

1.4.4

### Minecraft Version

1.21.1

### (Neo)Forge Version

neo 21.1.69

### Modpack & Version

FTB Presents Direwolf20 1.21 1.3.0

### Do you have optifine or Rubidium installed?

I have other rendering based mods installed

### Describe the issue

Block breaker is not consuming the engergy on the atomic disassembler

### Steps to reproduce

1. Load into world
2. Place simple block breaker down
3. Put the atomic disassembler from Mekanism into the block breaker
4. Place block in front of block breaker
5. Allow block to be broken
6. Open block breaker ui
7. Notice the Energy has not been consumed on the atomic disassembler

### Expected behaviour

To consume the energy of the atomic disassembler on use.

### Additional information

Issue originally reported to the FTB mopdack issue tracker https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5943

**Comment by Direwolf20-MC** [comment]
This is likely not something I can address on my side - sorry!

**Comment by thiakil** [comment]
Surely you should be calling `net.minecraft.world.item.Item#mineBlock` on the item used? That would cause energy to be used
