### ISSUE TITLE
[Request] Crushing/Smashing Upgrade Module

### ISSUE THREAD

**Issue by DizzyDJW** [Direwolf20-MC/JustDireThings#228]
### Describe the feature you'd like to have added

Honestly a module that allows for a way to make a cobbleworks that is self-contained within the JustDireThings mod would be awesome! Plus it has the added benefit of being useful while out mining.
On a Shovel, it converts gravel to sand.
On a Pickaxe, it converts any mined stone (which turns to cobble by default) into gravel. (If the smelt is left on or the pickaxe has silk touch, any stone you would normally get is converted into cobblestone, just cuz it'd be funny)

You can add some useful unique features to the module when used on other blocks, maybe compacted blocks drop 9 of the resources that make them up, or dust ores like Redstone and Glowstone have a chance to drop more dust, and maybe even allow dirt to get you sand, for a MUCH easier way to obtain lots of sand.

**Comment by Direwolf20-MC** [comment]
I'll consider this as an option, but its not a big priority right now :).  Thanks for the suggestion though!
