### ISSUE TITLE
blacklist fluids

### ISSUE THREAD

**Issue by Github-User4769** [Direwolf20-MC/JustDireThings#229]
### Describe the feature you'd like to have added

playing crafotria and wanted a lava bucket farm using dripstone and cauldrons with advanced clickers doing the pulling from the cauldrons.

turns out, I can't blacklist fluids using the clicker.
I would love that as a feature so I wouldn't need to time the clicker and the laser node so they don't sync.

**Comment by Direwolf20-MC** [comment]
Resolved in next version - thank you!
