### ISSUE TITLE
Able to read inventory with Advanced Sensor

### ISSUE THREAD

**Issue by tjsd** [Direwolf20-MC/JustDireThings#231]
### Describe the feature you'd like to have added

I am trying to automate the crafter in vanilla minecraft, and would like to trigger it based on the ammount of an item inside an inventory. 
![image](https://github.com/user-attachments/assets/be6cb2cc-1af5-47fe-b56d-1b628abb934c)
I have 2 Polymorphic Catalyst inside the chest and would then get a redstone signal. 

Also to support the vanilla crafter one would need to pulse the crafter. Could there be an option to output pulse as well?

**Comment by Direwolf20-MC** [comment]
This can be accomplished with another mod of mine - LaserIO.  I'd rather not recreate that functionality here :).
