### ISSUE TITLE
QOL - Clear glass and Illumination suggestions

### ISSUE THREAD

**Issue by tjsd** [Direwolf20-MC/JustDireThings#232]
### Describe the feature you'd like to have added

I would love if you included clear glass with connected texture and illuminated versions with glowstone.
They could be made in the stonecutter or a special recipe like cook the glass again in a furnace.

This is just so I do not have to add mods just for this.

I also hope you can look into a feral flare lantern version of lighting. Feed it glowstone dust and it lights up a huge area :)
The block itself could look like a energy transmitter but glowing yellow instead of red.

**Comment by Direwolf20-MC** [comment]
I'd rather not add these, as plenty of other mods add similar things :).  Thank you for the suggestion though!
