### ISSUE TITLE
Add Project: Vibrant Journeys short grass support to the lawnmower upgrade

### ISSUE THREAD

**Issue by Gaz492** [Direwolf20-MC/JustDireThings#234]
### Describe the feature you'd like to have added

Add support for Project: Vibrant Journeys short grass to the lawnmower upgrade

### Additional information

Forwarding an issue opened on the FTB modpack issue tracker
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5967

**Comment by Direwolf20-MC** [comment]
This can be added via a datapack :).
