### ISSUE TITLE
Stable footing from apothic enchanting doesn't work with dire upgrade flight

### ISSUE THREAD

**Issue by jinkhya** [Direwolf20-MC/JustDireThings#236]
### Just Dire Things version

1.4.4

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.66 

### Modpack & Version

ATM10  - 0.66

### Do you have optifine or Rubidium installed?

I have other rendering based mods installed

### Describe the issue

When breaking blocks while flying , the enchant Stable footing is supposed to negate the mining speed penalty. It doesn't seem to work when flying with the upgrade flight on the armor. 

### Steps to reproduce

1. Equip direthings chestplate with flying upgrade
2. Enchant boots (from vanilla or any mod) with stable footing from Apothic Enchanting mod
3. Double jump to fly
4. Place and break Obsidian while flying first, and then while not flying. (Reason behind obsidian block is because it's a hard block to break and it's more noticeable if it takes longer to break)

### Expected behaviour

The speed should be the same and it's currently slower while flying.

### Additional information

Rendering mods : Sodium, Sodium extra, Iris

**Comment by Direwolf20-MC** [comment]
I just tested this - my chestplate negates the penalty for flying, and the enchant from Apotheosis is also speeding things up, so in fact, with the apotheosis enchant, you actually mine FASTER when flying with my chestplate, not slower :).  I don't know if theres an easy way to fix this though. So I'll have to just let it be.
