### ISSUE TITLE
Allow energy transmitter to charge items in player's inventory

### ISSUE THREAD

**Issue by Zurkie** [Direwolf20-MC/JustDireThings#237]
### Describe the feature you'd like to have added

Would be cool if energy transmitter (or a new/alternate iteration of this machine) could charge items that require energy in player's inventory when standing within designated area. In addition to this, maybe tiered energy holding batteries would be nice as a way to move on from the Pocket Generator later in the game.

**Comment by Direwolf20-MC** [comment]
I don't think I want it to do that, but I'll consider it :)
