### ISSUE TITLE
time warper block

### ISSUE THREAD

**Issue by delta2k** [Direwolf20-MC/JustDireThings#238]
### Describe the feature you'd like to have added

Just like the wand but in block format. So i don't have to automate the wand using multiple blocks and item transfers. Would be also nice to do it in one block. simple warper and advanced block. also Then i can filter what blocks in an area get speed accelerated.

**Comment by Direwolf20-MC** [comment]
Its something I've considered, but for now, you can use the wand in a clicker.  I sort of like the fact that you have to work hard to automate that thing ;)
