### ISSUE TITLE
[bug] double text showing in machines.

### ISSUE THREAD

**Issue by delta2k** [Direwolf20-MC/JustDireThings#241]
### Just Dire Things version

1.4.4

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.72

### Modpack & Version

all the mods 10 (10.1.2)

### Do you have optifine or Rubidium installed?

None

### Describe the issue

double text showing up in the advanced clicker on target button

### Steps to reproduce

have a xp holder and advanced clicker. 
move the bounding box from default location. then
copy all settings with the machines settings copier and 
then paste them to the clicker. then you see double text and you can't telll what your reading in the target box button

### Screenshots

![Screenshot_570](https://github.com/user-attachments/assets/f87e1bb4-b4c8-4a41-bba6-654abcbaeb23)

**Comment by delta2k** [comment]
close and delete asp wrong screnshot

**Comment by delta2k** [comment]
![Screenshot_570](https://github.com/user-attachments/assets/f87e1bb4-b4c8-4a41-bba6-654abcbaeb23)

**Comment by Direwolf20-MC** [comment]
This should be resolved in 1.4.5 - please let me know if not :)
