### ISSUE TITLE
Feature suggestion: Wardrobe tool

### ISSUE THREAD

**Issue by bbarry** [Direwolf20-MC/JustDireThings#247]
### Describe the feature you'd like to have added

I would like to see a tool at the Celestigem/Eclipse level that you could bind and name a set of inventory holder blocks with and would open a radial menu to let your take off and put on gear. 

The tool should have behaviors:

* bind and name player inventory blocks to a radial menu position
* menu mode: store gear to inventory
* menu mode: equip inventory
* menu mode: swap to inventory (any gear you are wearing the is locked in any bound inventory would be placed in that inventory and the gear from the selected inventory would be equiped)

**Comment by Direwolf20-MC** [comment]
Its definitely something I've considered :).  Something like this is on the roadmap, but will require some time to add.
