### ISSUE TITLE
Suggestion: Hoes

### ISSUE THREAD

**Issue by anexusarchon** [Direwolf20-MC/JustDireThings#25]
Since hoes are the fastest tool for mining Plants, Sponges and Fungi; For example: Leaves, Hay Bayles, Nether Wart Blocks, Sculk, and Shroomlights, could we get ore mine for these types of blocks?

**Comment by AllieWade** [comment]
Seconding this, having a hoe to veinmine sculk wouldn't hurt my feelings even a little bit.

**Comment by Direwolf20-MC** [comment]
I wasn't comfortable with the idea of OreMiner - so instead I added the hammer ability to hoes - it will work in 3x3 5x5 or 7x7 on all Hoe breakable blocks :).  Hopefully that works?

As a bonus, you can now till the ground in an area using the hammer ability as well :)
