### ISSUE TITLE
How to use Potion Canister?

### ISSUE THREAD

**Issue by Wynnefox** [Direwolf20-MC/JustDireThings#253]
### Describe the feature you'd like to have added

I did some searches and I can't figure out how to use the potion canister besides an upgrade with bows? I can't even find if there is a video and don't see anything. So now I have my potion fluid stuck in a potion canister. Idealy either like to be able to just drink straight from it. Or maybe an injector I can put bottles or the canister in to use the potions on myself.

Thank you for time to read. Have a good day.

**Comment by Direwolf20-MC** [comment]
Currently its only use is the arrows.  I've got plans to expand the use, I just need to flesh them out. Thanks!
