### ISSUE TITLE
Pardox machine bug

### ISSUE THREAD

**Issue by Quantin99** [Direwolf20-MC/JustDireThings#254]
### Just Dire Things version

1.4.4

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.69

### Modpack & Version

Direwolf 20 1.3.0

### Do you have optifine or Rubidium installed?

No

### Describe the issue

The Paradox Machine doesn't work at all, even following the video, it doesn't create the paradox from a block and therefore doesn't recreate it once broken.

### Steps to reproduce

1 Put it in the same version as me
2 Create a solo world
3 Setup the machine
4 Try it out

### Expected behaviour

Resolution or explanation of the problem

### Screenshots

Setup
![2024-10-26_22 10 41](https://github.com/user-attachments/assets/da3bf375-8a12-4bfa-931a-f7c249442d28)
![2024-10-26_22 11 26](https://github.com/user-attachments/assets/ff7d53b0-c732-4bab-9dd7-696530e3e67f)
![2024-10-26_22 10 35](https://github.com/user-attachments/assets/4859f117-7939-4e6c-88ae-cc1241b5f76c)

**Comment by Direwolf20-MC** [comment]
The paradox machine only works on ores. Read the in game guide on how to use it :)

**Comment by Quantin99** [comment]
Thanks you ! :) I would like to take this opportunity to say that the mod is incredible!
