### ISSUE TITLE
Creature Catcher Crashes Game when put in Backpack

### ISSUE THREAD

**Issue by Aloneatwar13** [Direwolf20-MC/JustDireThings#255]
### Just Dire Things version

1.4.6

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.72

### Modpack & Version

Craftoria-1.6.0

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Creature Catcher with Strider that was stacked crashes game when put in backpack

### Steps to reproduce

1. Use creature catcher on top Strider that is stacked two high in the nether.
2. Open diamond tier backpack from Sophisticated Backpacks mod v1.21-3.20.17.1113.
3. Shift click creature catcher with captured Strider into backpack.
4. Game Crashes

### Expected behaviour

No Game Crash

### Log files

[latest.log](https://github.com/user-attachments/files/17532278/latest.log)
[debug.log](https://github.com/user-attachments/files/17532280/debug.log)

### Additional information

I am running my own dedicated server on a separate pc. I have tested this with normal mobs, non stacked striders, and a strider that I captured then released on land so that it was in the "freezing" state and then recaptured it.  All of these things did not crash my game when I put them into my backpack. Only the stacked strider that was captured and then put into the backpack has caused this problem so far.

**Comment by Direwolf20-MC** [comment]
I'm gonna think this might be on the backpack side of things, and probably not on mine.
