### ISSUE TITLE
Pickaxe Upgrades Applied To Direwolf20 Mining Gadget In Offhand

### ISSUE THREAD

**Issue by myanceyiii** [Direwolf20-MC/JustDireThings#257]
### Just Dire Things version

1.4.2

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.61

### Modpack & Version

FTB Presents: Direwolf20 - Season 14 - 1.2.1

### Do you have optifine or Rubidium installed?

I have other rendering based mods installed

### Describe the issue

When mining gadget is in off-hand with Just Dire Things pickaxe held in main hand, upgrade effects (efficiency, fortune, etc.) are applied to the mining gadget, costing durability on the pickaxe. And efficiency seems to stack with Mining Gadget upgrades...makes for some VERY fast mining...

### Steps to reproduce

1. Place mining gadget in off-hand.
2. Place upgraded Just Dire Things pickaxe in main hand.
3. Mine with mining gadget.
4. Profit.

### Expected behaviour

Pickaxe upgrades should not be applied to mining gadget.

**Comment by Direwolf20-MC** [comment]
I knew about this one, and can't come up with a good solution. Consider it a fun side effect :)

**Comment by myanceyiii** [comment]
😂😂 Amazing. At least now I don't feel like I'm cheating lol
