### ISSUE TITLE
Eclipse alloy pickaxe reset mining progress when charged

### ISSUE THREAD

**Issue by YocyCraft** [Direwolf20-MC/JustDireThings#261]
### Just Dire Things version

1.4.6

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.72

### Do you have optifine or Rubidium installed?

None

### Describe the issue

When you mining block with eclipse alloy pickaxe, and it get charged (for example by pocket generator), the mining progress will be reset. Maybe other electric mining tools have the same issue.

### Steps to reproduce

1. Build a setup like this:
![2024-10-29_21 14 07](https://github.com/user-attachments/assets/70e47f71-f783-4b02-aeb4-9ec76b0833ab)
2. Put an eclipse alloy pickaxe with non-full energy in your hand.
3. Put a pocket generator in the dropper.
4. Press button, and start mining netherite block.
5. After dropper activated, pocket generator get into player's inventory and eclipse alloy pickaxe get charged.
6. Mining progress was reset.

### Expected behaviour

Mining progress should not reset when pickaxe being charged.

### Screenshots

https://github.com/user-attachments/assets/be46f383-45d2-497a-a74e-de5512a19576

https://github.com/user-attachments/assets/59542bba-8e8c-469e-8c0a-228fa330aec5

### Log files

https://mclo.gs/1DjnGli

### Additional information

I've tested for Mekanism's atomic disassembler and it doesn't have the same issue.

**Comment by Direwolf20-MC** [comment]
Should be fixed now, thanks!
