### ISSUE TITLE
add button to enable/disable particle effects

### ISSUE THREAD

**Issue by Zurkie** [Direwolf20-MC/JustDireThings#262]
### Describe the feature you'd like to have added

Specifically to Energy Transmitter, Item Collector, and Experience Holder. The particle effects are cool, but sometimes I'd like to have them hidden.

Button toggle in the individual machine's GUI would be cool

**Comment by Zurkie** [comment]
I realised Energy Transmitter already has this option

**Comment by Direwolf20-MC** [comment]
Added - thanks :)
