### ISSUE TITLE
Extinguish upgrade triggers and causes durability loss in spectator mode

### ISSUE THREAD

**Issue by qb42** [Direwolf20-MC/JustDireThings#263]
### Just Dire Things version

1.4.4

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.69

### Modpack & Version

Direwolf20 1.21 1.3.0

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Extinguish upgrade on a Blazegold Chestplate triggers and causes the chestplate to lose durability when flying through lava even in spectator mode.

### Steps to reproduce

1. Wear a Blazegold Chestplate with the Extinguish upgrade
2. Switch to spectator mode
3. Fly through lava
4. You will hear the upgrade trigger and can see that the chestplate loses 25 durability

### Expected behaviour

Either nothing or for it to trigger with no durability loss

### Additional information

Interestingly this issue doesn't seem to occur with fire, in both creative and spectator mode extinguish doesn't trigger at all.
Lava in creative mode causes it to trigger with no durability loss.

Arguably related to https://github.com/Direwolf20-MC/JustDireThings/issues/103, one solution to both would be to just disable extinguish entirely when in creative or spectator.

I have not tested any other upgrades/armors yet.

**Comment by Direwolf20-MC** [comment]
I would argue this is more a vanilla bug, since I wouldn't expect a spectator to be able to be 'on fire' - but i added code to prevent this anyway :). Thanks for the report! I always forget spectator is a thing....

**Comment by qb42** [comment]
Thank you. Yeah the way vanilla handles this is weird, it looks like they set you on fire regardless then clear it the next tick if player.fireImmune() is true. I guess that's so the fire overlay still appears in creative. And the reason there's no durability loss in creative is because of the hacky way they handle that for all items (save the durability at the start of the tick, run everything as normal, then restore it later).
