### ISSUE TITLE
Dupe bug with JustDireThings tool upgrades.

### ISSUE THREAD

**Issue by Jaffiss** [Direwolf20-MC/JustDireThings#264]
### Just Dire Things version

1.4.6

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.72

### Modpack & Version

AllTheMods10 1.6

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Duplication of JustDireThings tool Upgrades

### Steps to reproduce

When placing a JustDirethings tool into a glowing itemframe, all the upgrades are ejected (duplicated) as they can be gathered up and still exist on the tool when removed from the frame.

### Expected behaviour

upgrades should not be ejected

**Comment by lpacphantom** [comment]
Just found this myself and wanted to make sure it was reported. Note, doesn't need to be a glowing item frame, happens with the normal one too.

**Comment by Direwolf20-MC** [comment]
Unfortunately this is actually a bug on Forge's side. Its either dupe when inserting into item frames, or don't drop the upgrades when the tool breaks, because the same event is fired for both :(
