### ISSUE TITLE
Time wand is showing wrong insuficient fluid message.

### ISSUE THREAD

**Issue by Gaz492** [Direwolf20-MC/JustDireThings#265]
### Just Dire Things version

1.4.4

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.69

### Modpack & Version

Direwolf20 - 1.21

### Do you have optifine or Rubidium installed?

I have other rendering based mods installed

### Describe the issue

The time wand is showing the insuficient fluid message for the portal wand

### Steps to reproduce

1. Empty your fluid out of your time wand
2. Try to tick accelerate anything

### Expected behaviour

Shows correct insuficient fluid message

### Additional information

Lang key is pointing to the portal message https://github.com/Direwolf20-MC/JustDireThings/blob/main/src/main/java/com/direwolf20/justdirethings/common/items/TimeWand.java#L111

**Comment by Direwolf20-MC** [comment]
Should be resolved :)
