### ISSUE TITLE
Advanced Clicker does not (always) break flowers

### ISSUE THREAD

**Issue by Epicycle23** [Direwolf20-MC/JustDireThings#268]
### Just Dire Things version

1.4.6

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.73

### Modpack & Version

All the Mods 10-1.15

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Advanced Clicker does not break flowers

### Steps to reproduce

1. Setup a passive mob farm using delightful dirt (golden egg)
2. Place a advanced clicker covering the 5x5 area using a left click (with or without a tool doesn't seem to matter)
3. Wait for grass and flowers to spawn and place some flowers manually
4. Grass gets broken but flowers won't "sometimes" also flowers get broken but not always seems to work better when manually placed though

### Expected behaviour

The advanced clicker will break flowers consistently

**Comment by Direwolf20-MC** [comment]
The clicker isn’t meant to be a breaker :). Use the advanced breaker instead.
