### ISSUE TITLE
Blazebloom soil does not autoharvest melons or pumpkins

### ISSUE THREAD

**Issue by Rithenar** [Direwolf20-MC/JustDireThings#269]
### Just Dire Things version

1.4.4

### Minecraft Version

1.21.1

### Modpack & Version

Direwolf20 1.21 1.3.0

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Melons and Pumpkins are not being automatically harvested when planted on blazebloom soil

### Steps to reproduce

Plant the pump/melon on blaze soil with 4 regular dirt blocks around it. When it grows, it just sits there without being harvested

### Expected behaviour

melon gets harvested

**Comment by Rithenar** [comment]
The NeoForge version is 21.1.69

**Comment by Direwolf20-MC** [comment]
Update :)

**Comment by Rithenar** [comment]
Do you know why it doesn't show an upgrade on FTB launcher? 
![image](https://github.com/user-attachments/assets/6367f023-968d-419c-8de6-52a594e09473)

**Comment by Rithenar** [comment]
Also updated to 1.4.7 and replanted melon. Still will not auto-harvest

![image](https://github.com/user-attachments/assets/ed3a3ad1-185b-4232-8cfa-d7840dcb97ba)
