### ISSUE TITLE
[Balance Suggestion] Ferricore Pickaxe ore scanner trivializes finding ancient debris

### ISSUE THREAD

**Issue by kizdude** [Direwolf20-MC/JustDireThings#27]
The ore scanner ability on the Ferricore Pickaxe allows you to almost instantly find ancient debris is the nether since they spawn in veins of 1 and 2 which is really easy to spot. The opportunity cost makes this basically a cheese strategy for farming netherite in the early to mid game.

Making the ore scanner ability only detect netherite (or even any ores that require a diamond level pickaxe or greater to mine) when using the Blazegold Pickaxe and up will solve this.

**Comment by Direwolf20-MC** [comment]
My initial reaction to this suggestion was that I didn't like it - especially since it only applied to ancient debris.  But then I considered that other mods might be adding other tiers so....sure :).  Now, the pickaxes can only scan for ores that they are the appropriate 'tier' to break :).
