### ISSUE TITLE
Blazebloom soil tick acceleration does not seem to affect Farmer's Delight tomatos

### ISSUE THREAD

**Issue by Rithenar** [Direwolf20-MC/JustDireThings#270]
### Just Dire Things version

1.4.4

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.69

### Modpack & Version

DW20 1.21 1.3.0

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Tomatos not growing at same slight accelerated speed than other crops

### Steps to reproduce

Plant tomatos and other crops. For each 20-30 other crops you get 1 tomato

### Expected behaviour

tomatos to grow faster like other things planted

**Comment by Direwolf20-MC** [comment]
It looks like these crops use a custom type of block that I won't be able to detect unfortunately. Crops in Minecraft are very non-standard, so i just won't be able to account for all of them :(
