### ISSUE TITLE
Make Just Dire Things Ore compatible with Theurgy

### ISSUE THREAD

**Issue by Rithenar** [Direwolf20-MC/JustDireThings#271]
### Describe the feature you'd like to have added

Theurgy is a good alternative for relatively early game ore processing. Raw materials from JDT are tagged as raw materials but the Liquefaction Cauldron will not accept them as they need the #theurgy:raw_materials tag. Example of the tag from Raw Iron:

![image](https://github.com/user-attachments/assets/afc44378-10b2-489c-9f2f-30570c2dabcc)

**Comment by Direwolf20-MC** [comment]
This can be added by pack makers :).
