### ISSUE TITLE
Axe with treefeller and smelting upgrade (charcoal farm) doesn't cut entire spruce tree

### ISSUE THREAD

**Issue by TJM** [Direwolf20-MC/JustDireThings#272]
### Just Dire Things version

1.4.4

### Minecraft Version

1.21.0

### (Neo)Forge Version

21.1.69

### Modpack & Version

Direwofl20 1.21 1.3.0

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Axe with treefeller and smelting upgrade (charcoal farm) doesn't cut entire spruce tree

### Steps to reproduce

1. plant at least 4x4 spruce saplings (I used the advanced block placer, so it was a 7x7 block of saplings)
2. Grow it (bone meal or wait)
3. Create a dire things axe (celestegem), with the treefeller and smelting upgrade
4. After the spruce tree has grown, usually it is 4x4 and quite tall (10-15+ blocks)
5. try to cut the tree with the axe above
6. The tree is only partially cut down (see screenshot)

### Expected behaviour

The entire tree should be cut down, and smelted to coal

### Screenshots

![2024-11-04_09 46 45](https://github.com/user-attachments/assets/7eae8a31-2cae-4138-ae9e-90e10d4befea)

### Additional information

This seems to be a problem with the smelter, because if you disable the smelting upgrade, the treefeller axe works fine.

**Comment by Direwolf20-MC** [comment]
Can you tell me if the eclipse alloy can do it. Higher tier axes can treefell larger trees at once.

**Comment by TJM** [comment]
I can't make that yet, but I could probably test in a creative world. I did find that the treefeller itself even fails on the full size ones. 
![2024-11-04_10 18 25](https://github.com/user-attachments/assets/ba71d639-754e-4cc3-8a94-eed88a72437d)

**Comment by TJM** [comment]
Confirmed, the eclipse alloy axe did work as expected. Does that mean it is a feature, not a bug? :) 

I guess it would have been more clear if it had cleanly limited at 12 blocks or whatever, and not left a zig-zag pattern...

**Comment by Direwolf20-MC** [comment]
I agree the pattern is weird :). But yea, working as intended. The higher tier tools can break more blocks at a time.
