### ISSUE TITLE
Armor/Items rapidly discharging w/ red line across the screen

### ISSUE THREAD

**Issue by Zyrille** [Direwolf20-MC/JustDireThings#274]
### Just Dire Things version

1.4.6

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.72

### Modpack & Version

Craftoria 1.6.1

### Do you have optifine or Rubidium installed?

None

### Describe the issue

A bug happened where there's a red line across my screen along the energy display of the armor/item, its rapidly eating the power (drained billions of FE in seconds) and the energy description on the items are in the negatives.

### Steps to reproduce

Unsure how to reproduce the issue, its happened to me twice and nothing would fix it until I basically deleted the item. It happens on both armor and items that is being charged wirelessly in my inventory via powah's player transmitter. 

### Screenshots

<img width="461" alt="HVMD6acl" src="https://github.com/user-attachments/assets/35d47892-342d-448b-b9e6-040672440b6c">

![image](https://github.com/user-attachments/assets/ff9e7e42-2214-4d2d-b12a-471c7f573cf7)

### Log files

https://mclo.gs/c7cjEQJ

**Comment by Direwolf20-MC** [comment]
I've tried a bunch, but I can't seem to replicate this. If you find a way to cause it to happen please let me know :).  For now I have to assume its some kind of cross mod compatibility issue, but if you find a way to repeat this reliably please re-open
