### ISSUE TITLE
Teleporting Drops

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [Direwolf20-MC/JustDireThings#275]
### Just Dire Things version

1.4.6

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.72

### Modpack & Version

Craftoria 1.6.1

### Do you have optifine or Rubidium installed?

I have other rendering based mods installed

### Describe the issue

On a server, ALL JDT tools whether they have the ability to teleport dropped items or not, seem to be dropping their items AND exp at a specific set of coordinates being: 6127, 67, -3643.

Edit: It's teleporting items and xp to those coords in every dimensions respectively. You break something in the overworld, it goes to those coords in the overworld. you break something in the mining dim, it goes to those coords in the mining dim, etc.

### Steps to reproduce

Honestly, there is no errors I can find nor anything in the logs. It's a total mystery.

### Expected behaviour

Not... teleport  items randomly.

### Screenshots

https://github.com/user-attachments/assets/d3ea75d6-07f7-4ab3-94e1-1eefb1db9598

https://github.com/user-attachments/assets/d179262f-3fd6-47e5-afc1-5413784ee21c

### Log files

https://gist.github.com/Kazuhiko-Gushiken/d0378b2c7b3be1b12aeaea412628b9a3

### Additional information

Sodium is the main one

**Comment by Kazuhiko-Gushiken** [comment]
> I can't imagine how this could be possibly happening from Just Dire Things alone - but I also can't rule out that there isn't something wrong with my mod :).
> 
> Is there any chance you can help me figure out how to replicate this?

I can def try, but I wouldn't know the first place to start. It was so random, just started happening randomly and only with JDT tools.  I'll ask around the server to see if they remember doing anything pre-item teleporting.

**Comment by solly1997** [comment]
Describe the issue
this issue happend at my base  
i wanted to see if breaking a waystone with silktouch  pickaxe would still hold its data , 
i broke it from the top half of the learned waystone with this paxel 
and it started spraying items and xp from the middle of the waystone 
i also had simple breakers in the same chunk with more JDT pickaxes if that have something to do with it 
also non if my tools have teleport upgrade 
hope that helps
![2024-11-11_23 15 46](https://github.com/user-attachments/assets/e2c7b1ec-d9b9-4b3a-b8e8-b805ad2c844a)
 
![2024-11-11_23 23 14](https://github.com/user-attachments/assets/9eeea853-bdb8-449f-b9a1-8eb2aa3c413d)
