### ISSUE TITLE
Budding Time Crystal Block cannot be included in AE2 Spatial Storage

### ISSUE THREAD

**Issue by adamgoose** [Direwolf20-MC/JustDireThings#276]
### Just Dire Things version

1.4.6

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.72

### Modpack & Version

Craftoria - 1.21.1 (1.6.1)

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Attempting to capture a Budding Time Crystal block in AE2 Spatial Storage leaves the block in place.

### Steps to reproduce

1. Spawn in the Overworld
2. Create a 3x3x3 (internal) Spatial Storage system with AE2
3. Place a Budding Time Crystal Block in the world within the Spatial Pylons
4. Place another block within the pylons for sanity
5. Give the Spatial IO Port a redstone signal
6. Observe the "other block" disappear into the Spatial Storage, while the Budding Time Crystal Block remains

### Expected behaviour

Budding Time Crystal Blocks can be captured by AE2 Spatial Storage

**Comment by Direwolf20-MC** [comment]
It seems to work in my test world, it may be something specific to the pack you're playing? Nothing i'm doing should be preventing this - as far as I know.

![image](https://github.com/user-attachments/assets/1217669e-8132-4c69-9e04-925b6e8a9711)
![image](https://github.com/user-attachments/assets/80ef408d-d174-4ef8-8988-266653460232)
