### ISSUE TITLE
Unbreaking enchant for T1 and T2 bows

### ISSUE THREAD

**Issue by MuteTiefling** [Direwolf20-MC/JustDireThings#277]
### Just Dire Things version

1.4.8

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.74

### Modpack & Version

Enigmatica 10

### Do you have optifine or Rubidium installed?

Yes

### Describe the issue

Tier 1 and 2 Bows cannot be enchanted with Unbreaking

### Steps to reproduce

The bows specifically are missing the `#minecraft:enchantable/durability` tag, where the other equipment at these tiers is not. 

We're uncertain if this is intended, but it seems a bit odd considering the other items can have unbreaking. 

### Expected behaviour

Ability to enchant with Unbreaking

### Additional information

Rendering: Sodium/Iris

https://github.com/EnigmaticaModpacks/Enigmatica10/issues/212

**Comment by Direwolf20-MC** [comment]
You are correct! I'm not entirely sure how vanilla bow's get this enchant, because i assumed it came from the bow_item tag but I added the durability tag to all my bows, since the powered ones will use less power (per shot) when enchanted with unbreaking.
