### ISSUE TITLE
Portal gun missing localised strings when using subtitles. 

### ISSUE THREAD

**Issue by moshhh** [Direwolf20-MC/JustDireThings#278]
### Just Dire Things version

1.4.9

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.72

### Do you have optifine or Rubidium installed?

None

### Describe the issue

The portal gun is missing localised strings when using the subtitle feature. Instead the full string (sound.justdirethings.portal_gun_*) is displayed.

### Steps to reproduce

1. Turn on subtitles under Options --> Music & Sounds
2. Use the portal gun.
3. sound.justdirethings.portal_gun_open or sound.justdirethings.portal_gun_close are displayed.

### Expected behaviour

A localised string displayed. 

### Screenshots

![2024-11-13_10 53 37](https://github.com/user-attachments/assets/4810467d-fa93-4158-8c70-bd39da5343da)
![2024-11-13_10 53 43](https://github.com/user-attachments/assets/d1819dc5-7e11-48fb-a284-9e6bb114f585)

**Comment by Direwolf20-MC** [comment]
This has been resolved :)
