### ISSUE TITLE
[Feature Request] Add Batteries which can be carried in a player's inventory or curio slots. 

### ISSUE THREAD

**Issue by moshhh** [Direwolf20-MC/JustDireThings#279]
### Describe the feature you'd like to have added

The pocket generator is great if you're using it to generate power for your tools, but if you have another power source you're relying on other mods' batteries or tools to keep your tools powered. In your own let's play you're using a player transmitter from powah for example. Further, the pocket generator's cap at 1,000,000FE is insufficient when using eclipse-alloy tier tools and armour. I'd rather not include powah or another mod just for its batteries feature. 

I suggest that each tier of alloy/gem receives its own battery in increasing capacities to complement the pocket generator and facilitate using other mods' power generation to complement `Just Dire Things`.  This could function similarly to the fluid canister with its fill mode functionality.

**Comment by Direwolf20-MC** [comment]
Lots of other mods add batteries, so at this time I don't have a desire to add any. I'll consider it as a potential future addition though
