### ISSUE TITLE
[Bug] Lawnmower ability does not break fern blocks

### ISSUE THREAD

**Issue by kizdude** [Direwolf20-MC/JustDireThings#28]
The lawnmower ability currently doesn't break the `minecraft:fern` or `minecraft:large_fern blocks even though they share all of the characteristics of grass.

Here is an image of the result of me using the ability in a sparse jungle biome:

![image](https://github.com/Direwolf20-MC/JustDireThings/assets/39441658/55f0f7c3-d059-42a7-8d2a-cd6ac5fb03e2)

**Comment by Direwolf20-MC** [comment]
Thanks for the report! Fixed in dev - will be in the next version :)
