### ISSUE TITLE
Upgrade dupe with ally

### ISSUE THREAD

**Issue by Gaz492** [Direwolf20-MC/JustDireThings#280]
### Just Dire Things version

1.4.9

### Minecraft Version

1.21.1

### (Neo)Forge Version

neo 21.1.77

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Giving an ally a tool with upgrades attached will cause the upgrades to be dropped and kept on the tool

### Steps to reproduce

1. Find/Summon ally
2. Give tool such as ferricore axe with a treefeller upgrade to the ally
3. Watch the upgrades drop on the floor
4. Take tool back from ally and observe upgrades still attached 

### Expected behaviour

Not dupe the upgrades

### Additional information

I have a feeling this is probably the same issue as the item frame one https://github.com/Direwolf20-MC/JustDireThings/issues/264 but thought i would report just to be sure.
[](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6172)

**Comment by Direwolf20-MC** [comment]
Unfortunately this is a forge bug.
