### ISSUE TITLE
ATM10 Update 1.20 Includes Supplimentaries which causes the JDT Inventory Holder to CDT game

### ISSUE THREAD

**Issue by zeziba** [Direwolf20-MC/JustDireThings#283]
### Just Dire Things version

1.4.9

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.77

### Modpack & Version

ATM10 1.20

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Supplimentaries causes JDT Inventory Holder to CDT game

### Steps to reproduce

1. Have ATM10
2. Open MC
3. Place JDT inventory holders
4. Insert assorted armors including ATM armors
5. Wear cosmetic items

### Expected behaviour

Not to CDT

### Log files

https://gist.github.com/zeziba/3ecf6cec28318428b3be575700f13a57

### Additional information

The log states that JDTs failed to render due to

`Caused by: java.lang.ClassCastException: class com.direwolf20.justdirethings.client.blockentityrenders.InventoryHolderBER$1 cannot be cast to class net.mehvahdjukaar.supplementaries.api.IQuiverEntity (com.direwolf20.justdirethings.client.blockentityrenders.InventoryHolderBER$1 is in module justdirethings@1.4.9 of loader 'TRANSFORMER' @5950054d; net.mehvahdjukaar.supplementaries.api.IQuiverEntity is in module supplementaries@1.21-3.0.13-alpha of loader 'TRANSFORMER' @5950054d)`

If that is the be-all end-all no idea but here we are.

Issue in the ATM10 is https://github.com/AllTheMods/ATM-10/issues/1161

**Comment by oatmealmanFG** [comment]
even after a pack update that pushes supplimentaries back into the game, its broken. my son cant join my lan game unless we delete this broken mod

**Comment by zeziba** [comment]
@oatmealmanFG I just disable supplimentaries for the moment as it tends to cause a bunch of issues outside of just this Direwolf one. 


What I think the JDT's needs to add though is an ignore for errors like this though so they stop causing a CTD, logging it would be nice but that could be added to a config with an internal flag so that it doesn't spam the logs.

**Comment by Direwolf20-MC** [comment]
I installed Supplementaries in my dev instances, and it did not crash. However, it also wanted me to installed Ammendments (which may be the cause).  This mod caused my world to fail to load entirely - and i couldn't even create a new world.  

Based on the crash report you gave, and the fact that I couldn't even really get the mod to work - i'm going to assume this issue is on the supplementaries side. 

I'll add a try/catch to try to prevent the crash, but can't guarantee it'll work :)
