### ISSUE TITLE
[suggestion] Flight/elytra speed slider

### ISSUE THREAD

**Issue by mazunki** [Direwolf20-MC/JustDireThings#284]
Similar to how we have run/walk/swim speed, it would be nice to be able to accelerate creative flight. While the wands can replace rockets quite nicely for elytra-flight, there is still a max speed limit when we're not dashing with the wand. 

Repeatedly clicking the wand to travel long distance is not great for carpal tunnel. I am aware there's alternative travel methods for long(er) distances, but sometimes flight is just what we prefer.

Would having a slider to increase the (max?) velocity and/or acceleration rate for both of these make sense?

**Comment by Direwolf20-MC** [comment]
I'll add this to a potential future upgrade, but for now I'm happy with the speeds you can achieve with the wands + elytra and creative flight.
