### ISSUE TITLE
[suggestion] Potion belt

### ISSUE THREAD

**Issue by mazunki** [Direwolf20-MC/JustDireThings#285]
This might be out of scope, but I to think it's similar enough in spirit, and overlaps well with other aspects of the mod.

We already have a fuel canister, which works for the bow. It would be nice to have a standalone item (equippable in curios, ideally) which can hold potion canisters, and automatically applies them to the player under certain conditions, keybinds, or continuously. Perhaps with a delay for automatic consumption.

I also feel it would make sense to add tiers to both of these items. The fluid canister can increase its capacity, while the belt can increase the amount of canister it holds (up to 9?), support more conditions, and lowering the delay it takes to apply the effect.

**Comment by Direwolf20-MC** [comment]
I definitely plan to add more features for the potion canisters, so I'll take this under advisement :).
