### ISSUE TITLE
Block breaker gets stuck on fluids

### ISSUE THREAD

**Issue by cas-haaijman** [Direwolf20-MC/JustDireThings#286]
### Just Dire Things version

1.4.9

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.77 

### Modpack & Version

Craftoria 1.8.0

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Advanced Block Breaker stops with liquid in area

### Steps to reproduce

1. Open MC world
2. Obtain advanced block breaker and select highlight area + expand radius a bit
3. place liquid (like water) in some of the highlighted area and stone in the rest
4. add power and pickaxe to breaker
5. observe that no blocks are broken

### Expected behaviour

Block breaker should skip liquids, as they cannot be broken

**Comment by Direwolf20-MC** [comment]
Resolved - thank you!!
