### ISSUE TITLE
Unused frames in sprite

### ISSUE THREAD

**Issue by bookerthegeek** [Direwolf20-MC/JustDireThings#287]
### Just Dire Things version

1.4.9

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.75

### Modpack & Version

N/A

### Do you have optifine or Rubidium installed?

I have other rendering based mods installed

### Describe the issue

Their is an unused frames in sprites

### Steps to reproduce

1. Install mod
2. Start MC
3. Look at the log

### Expected behaviour

Not for the error to be in the log?

### Screenshots

N/A

### Log files

```shell
[Worker-ResourceReload-18/WARN] [minecraft/SpriteContents]: Unused frames in sprite justdirethings:item/creaturecatcher_top_animation: [8]
[Worker-ResourceReload-1/WARN] [minecraft/SpriteContents]: Unused frames in sprite justdirethings:item/creaturecatcher_side_animation: [8]
```

### Additional information

Saw this in the log, thought you might want to know about it. Don't know if it an issue or not, just more of an fyi for you. Love the mod!

**Comment by Direwolf20-MC** [comment]
Not an issue - thanks for the heads up though :)
