### ISSUE TITLE
Missing Sound

### ISSUE THREAD

**Issue by bookerthegeek** [Direwolf20-MC/JustDireThings#288]
### Just Dire Things version

1.4.9

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.75

### Modpack & Version

N/A

### Do you have optifine or Rubidium installed?

I have other rendering based mods installed

### Describe the issue

An event is missing a sound

### Steps to reproduce

1. Install mod
2. Start MC
3. Look at the log

### Expected behaviour

Not for the error to be in the log?

### Screenshots

N/A

### Log files

```shell
[Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: justdirethings:beep
```

### Additional information

Saw this in the log, thought you might want to know about it. Don't know if it an issue or not, just more of an fyi for you. Love the mod!

**Comment by Direwolf20-MC** [comment]
Fixed - thanks!
