### ISSUE TITLE
Ferricore Axe with Eternal Stella will not break the tree

### ISSUE THREAD

**Issue by tnthung** [Direwolf20-MC/JustDireThings#289]
### Just Dire Things version

1.4.6

### Minecraft Version

1.12.1

### (Neo)Forge Version

21.1.72

### Modpack & Version

ATM 10 - 1.7

### Do you have optifine or Rubidium installed?

None

### Describe the issue

The ferricore axe with tree feller alone worked fine. But it refuses to break the tree if eternal stella is installed.

### Steps to reproduce

1. Craft a ferricore axe
2. Install tree feller upgrade
3. Install Eternal Stella
4. Try breaking a tree

### Expected behaviour

The tree been chopped down and durability stay unchanged.

**Comment by Direwolf20-MC** [comment]
This should be fixed, thanks for the report!
