### ISSUE TITLE
Upgrade dupe with item frames

### ISSUE THREAD

**Issue by Tobselino** [Direwolf20-MC/JustDireThings#290]
### Just Dire Things version

1.4.9

### Minecraft Version

1.12.1

### (Neo)Forge Version

1.21.1

### Modpack & Version

Craftoria 1.21

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Upgrades drop when item is put in item frame. Item keeps the upgrades

### Steps to reproduce

1. Get JustDireThings Gear/Tool (i.e Celestigem Helmet)
2. Put Upgrade on Gear/Tool (e.g. Night Vision)
3. Put upgraded Gear/Tool in Item Frame
4. Pick up dropped (duped) Upgrades 
5. Get Gear/Tool out of Item Frame

### Expected behaviour

Gear/Tool to go into item frame without anything dropping

**Comment by Direwolf20-MC** [comment]
Unfortunately this is a bug in Forge :)
