### ISSUE TITLE
Simple Clicker causing crash on Farmer's Delight cutting board

### ISSUE THREAD

**Issue by tlion1069** [Direwolf20-MC/JustDireThings#293]
### Just Dire Things version

1.4.9

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.74

### Modpack & Version

FTB Evolution - 1.3.0

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Clicker right clicking on a FD cutting board produces an error

### Steps to reproduce

1. Place a Farmer's Delight cutting board
2. Place a Simple Clicker facing the cutting board
3. Make sure the Clicker is right-clicking and is not using any tools
4. Crash occurs

### Expected behaviour

Clicking on the cutting board... normally?

### Log files

[crash-2024-11-20_15.41.12-server.txt](https://github.com/user-attachments/files/17838239/crash-2024-11-20_15.41.12-server.txt)

**Comment by Direwolf20-MC** [comment]
Cannot reproduce, I strongly suspect this was on their side, so maybe they already fixed the bug :)
