### ISSUE TITLE
[Suggestion] Upgrade for block placer to activate multiple sides of a block

### ISSUE THREAD

**Issue by Dr69onS6mur6i** [Direwolf20-MC/JustDireThings#296]
### Describe the feature you'd like to have added

Right now the block placer can only activate on one face of a block. Using the placers for goo automation the way they are currently set up means you can only use one face at a time per machine. Having an upgrade of some kind that will allow placing on multiple faces of a block would help efficiently automating the goo materials.

**Comment by Direwolf20-MC** [comment]
I'll consider this, but I think it gets too complex too quickly. I'll add it to the possible feature list in the future
