### ISSUE TITLE
[Suggestion] Colorable or Visual changer of the tools

### ISSUE THREAD

**Issue by manaphoenix** [Direwolf20-MC/JustDireThings#298]
### Describe the feature you'd like to have added

Like the colored enchantment runes in Quark, useful for signifying the difference between different tools of the same kind /w different enchantments or uses.

Example:
Fortune pickaxe is changed to glow blue
Silk touch pickaxe is changed to glow yellow

**Comment by Direwolf20-MC** [comment]
Sorry, most other items don't have this, and it would be pretty challenging to implement. I'll pass for now, thanks for the suggestion though!
