### ISSUE TITLE
Eclipse Gate cannot be set to distance of 1

### ISSUE THREAD

**Issue by lpacphantom** [Direwolf20-MC/JustDireThings#299]
### Just Dire Things version

1.4.9

### Minecraft Version

1.21

### (Neo)Forge Version

21.1.74

### Modpack & Version

FTB Evolution

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Eclipse Gate doesn't stay on distance 1

### Steps to reproduce

1. Open Eclipse Gate Settings.
2. Set Distance to 1.
3. Press Escape to close settings.
4. Use wand, goes 2 blocks.
5. Re-opening settings shows it set to 2.

### Expected behaviour

Be allowed to use distance 1

**Comment by Direwolf20-MC** [comment]
I definitely have mine set to 1 in the DW20 pack. I’ll test it to be sure

**Comment by lpacphantom** [comment]
I've just messed around a bit and have managed to get it to set to 1, but only if I change it to 1 while it's set to activate on a custom binding. If I close it with it set to a binding, I can reopen and change it to be right click and it will stay on 1, but if I change the value when it's set to right click, it will update to 2 on its own.

**Comment by Direwolf20-MC** [comment]
I also can't replicate this - sorry ! If you manage to find a reliable way to cause it, let me know and feel free to re-open.
