### ISSUE TITLE
Wrong bow aiming rotation on left hand

### ISSUE THREAD

**Issue by ArukaAlter** [Direwolf20-MC/JustDireThings#300]
### Just Dire Things version

1.4.9

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.82

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Wrong bow rotation while on left hand

### Steps to reproduce

Pick any variant of the bow on the left hand (either as main left or offhand of right) and aim

### Expected behaviour

The bow model should aim to the front and not the sky

### Screenshots

![2024-11-27_19 42 37](https://github.com/user-attachments/assets/399b9a10-58e9-4f44-a0f9-475b03ad597f)

**Comment by Direwolf20-MC** [comment]
Resolved - thanks! :)
