### ISSUE TITLE
Ore Miner Upgrade break time greatly reduced when mining through a liquid

### ISSUE THREAD

**Issue by DevinProv** [Direwolf20-MC/JustDireThings#301]
### Just Dire Things version

1.4.8

### Minecraft Version

1.2.1

### (Neo)Forge Version

21.1.74

### Modpack & Version

Direwolf20 1.4.1

### Do you have optifine or Rubidium installed?

None

### Describe the issue

When mining through liquids using the Ore Miner upgrade the break time is greatly reduced

### Steps to reproduce

1. Stand on Vein
2. Place Bucket of Water under your feet 
3. Mine the vein.
 

### Screenshots

https://www.youtube.com/watch?v=66ixEW4sdR8
Short clip

**Comment by Direwolf20-MC** [comment]
I can't seem to reproduce this bug - do you have any enchants or something on your armor affecting break speed, especially when in water?

**Comment by DevinProv** [comment]
I was wrong to submit this bug and I apologize. I tested this with a simple Iron Pickaxe and was able to replicate this bug within my world. It seems to be a bug with some other mod within this version of the modpack. 
I was able to replicate this on a fresh world with nothing but a water bucket and a iron pickaxe.
Sorry to waste your time!

**Comment by Direwolf20-MC** [comment]
No problem :)
