### ISSUE TITLE
Advanced Portal Gun Persistent Portal

### ISSUE THREAD

**Issue by ItMeCorban** [Direwolf20-MC/JustDireThings#302]
### Describe the feature you'd like to have added

Hi! I left a comment with a similar suggestion but figured this is probably the better place for it.
I was wondering what you thought of an extra ability on the advanced portal gun to make persistent portals, like the regular portal gun does.

I don't think the current functionality of the advanced portal gun should be changed much so it would need some form of limiter, say one deployment at a time or a fluid and power cost per tick while the portal is kept open, or even both.

The persistent feature could be one of two things, either a left or shift left click with the gun will open a portal to the selected favourite, and close again when another persistent portal is opened, or a regular portal to the same favourite is opened. This would allow you quick back and forth access to a location say if you're setting something up, but won't need to regularly access it once it's setup.

The other way it could work would be an extra slot in the favourites wheel to function as the regular portal gun, allowing you to left and right click to place each side of the portal.

I guess this is almost an extension of the shift right click to return as it would allow you to keep a portal live for the duration you need it, rather than continuously opening a new portal back and forth.

Potentially this could be even more advanced allowing you to set a timeout for the portals in the same way you can set pickup delays etc in the regular just dire machines, but I worry that may be a bit too advanced and over powered, so perhaps would be better suited for a super advanced portal gun.

**Comment by Direwolf20-MC** [comment]
I'm not sure I want to add this - but I do want a block form of the portals, that you can build and have be persistent.
