### ISSUE TITLE
Feature Request: advanced player inventory

### ISSUE THREAD

**Issue by bbarry** [Direwolf20-MC/JustDireThings#303]
### Describe the feature you'd like to have added

I would like to see an advanced player inventory block which can be configured to remotely work on the player's inventory across dimensions with these capabilities:

1. power armor/tools/curios across dimensions
2. keep selected inventory slots filled (same/similar mechanism as the simple player inventory except automatic instead of a button click in the ui)
3. fill/empty JDT fluid canisters to a specific level
4. access player inventory in general (pull items out, put items in via laserio nodes or similar automations)
5. ignore/prevent access to specific slots from the inventory block

### Additional information

While you could alternatively (or additionally) fill just portal guns and time wands with their respective fluids, I feel like there is a compelling enough story to having exactly 3<x<5 buckets of water/lava/milk/etc on hand to justify the generic solution and allowing the existing canister function to move the fluid the rest of the way (automating milk into a JDT canister to auto fill buckets in player inventory for cooking recipes is a really neat little trick).

It might be preferable to restrict the game to only one advanced player inventory block per player and make the block operate on a tick frequency for server lag/item duplication glitch avoidance reasons. Perhaps an ingredient of a "contained paradox" or something like that could be necessary to acknowledge that restriction and ensure this block is firmly deep into the JDT endgame item set. Maybe we craft a "phenomenon catcher" by putting ender eyes/time crystals/celestigems around a creature catcher and then capture paradoxes (and other things like maybe weather) to use as a crafting ingredient.

**Comment by Direwolf20-MC** [comment]
I do have plans for an advanced form of the inventory block - some of these features were planned for it :).  Thanks for the suggestions! I'll consider adding some of the ones I hadn't thought of as well when I get around to doing it
