### ISSUE TITLE
Mining the Time Crystal for a silk touch

### ISSUE THREAD

**Issue by Markyps** [Direwolf20-MC/JustDireThings#305]
### Describe the feature you'd like to have added

![image](https://github.com/user-attachments/assets/56500038-343d-4755-a0fd-70b14ef72b14)
I wanted to diversify my modpack assembly and make a multiblock structure out of time crystals. But due to the fact that they cannot be obtained in the form of a block like amethysts

**Comment by Direwolf20-MC** [comment]
This has been added here:
https://github.com/Direwolf20-MC/JustDireThings/commit/fb4216ce35ab2937c4e2d8a58eefc9feac13b6d4

As a bonus, you'll also be able to silk touch all sizes of time Crystal, because thats how vanilla amethyst works too :)
