### ISSUE TITLE
Ore Miner not compatible with Deepslate Yellorite Ore from Extreme Reactors

### ISSUE THREAD

**Issue by katouriku** [Direwolf20-MC/JustDireThings#307]
### Just Dire Things version

1.4.9

### Minecraft Version

1.21.1

### Modpack & Version

21.1.82

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Ore Miner is not functioning while mining Deepslate Yellorite Ore

### Steps to reproduce

1. Mine Deepslate Yellorite Ore with a Ore Miner equipped pickaxe(bug was experienced using Ferricore although I don't imagine that's of consequence) 

### Expected behaviour

All ore to be mined and drops teleported to location of targeted block

### Additional information

I would request for some more config settings to be added to the mod. I've read through the config file and feel it's currently lacking some nice to haves like for example custom Ore Miner compatible blockID configuration. I think it would be much simpler on your end too to simply allow the user to configure additional unsupported blocks rather than having to add things in manually. I'd also request you add an option to change the mining duration multiplier as I'd rather not have veinmining take just as long as mining each ore separately. Also configurable saturation drain would be great as well(all options from other veinmining mods basically). Thanks a lot for the effort you and many others have put into making this mod. I absolutely love it and think with some minor tweaks and future content updates it'll become a staple of modded Minecraft. Love you dire <3

**Comment by Direwolf20-MC** [comment]
Ore miner works on any blocks tagged wjth ores or clusters. I suspect deep slate yellorium is missing that tag which would be a bug on their side :). 

You can add the tag using a data pack if you wish. Most of these kinds of things are tag based.

**Comment by katouriku** [comment]
> Ore miner works on any blocks tagged wjth ores or clusters. I suspect deep slate yellorium is missing that tag which would be a bug on their side :).
> 
> You can add the tag using a data pack if you wish. Most of these kinds of things are tag based.

Sincerest apologies. That makes way more sense. I myself was confused why this was occurring as I know almost everything is done on a tag basis nowadays but I figured JDT might be using a whitelist instead. I'll write up a report on Extreme Reactors page then. Thanks for replying so quickly and have a great rest of your day!
