### ISSUE TITLE
Sensors can't sense enough blocks

### ISSUE THREAD

**Issue by skinnypiggy** [Direwolf20-MC/JustDireThings#31]
Advanced sensors have the ability to detect an 11x11x11 space, but only the capability to sense up to 100 blocks in that space, making it a bit awkward. Please up the number to match the volume they detect.

**Comment by Direwolf20-MC** [comment]
Good point! It'll be fixed in the next version :)

https://github.com/Direwolf20-MC/JustDireThings/commit/35af555eefe3e74130ec3cb7bce2a4c543e2273b
