### ISSUE TITLE
Item Frame

### ISSUE THREAD

**Issue by Cptn-Slacker** [Direwolf20-MC/JustDireThings#314]
### Just Dire Things version

1.0

### Minecraft Version

1.21.1

### Modpack & Version

Direwolf season 14 latest

### Do you have optifine or Rubidium installed?

No

### Describe the issue

Putting just dire tools equipped with upgrades in item frames duplicates the upgrades

### Steps to reproduce

1. Equip a Just Dire pickaxe, axe, sword, etc with an upgrade or multiple upgrades.
2. Place the tool in an item frame

**Comment by Direwolf20-MC** [comment]
This is an issue in forge unfortunately.  I have a bug open over there to fix it.

**Comment by Cptn-Slacker** [comment]
Ok. Just wanted to make sure it was known.
