### ISSUE TITLE
Farmland issue with 2 phase crops

### ISSUE THREAD

**Issue by Winnmi** [Direwolf20-MC/JustDireThings#319]
### Just Dire Things version

1.5.1

### Minecraft Version

1.21

### Do you have optifine or Rubidium installed?

None

### Describe the issue

with your soil, plants like the tomato from Farmers Delight where the plant grows and then the fruit without destroying the plant itself at harvest, it destroys the plant and it takes ages to grow back

### Steps to reproduce

1. make a farm land with the Blazegold Hoe
2. plant the tomato
3. wait until the plant is grown and the tomato
4. if the farmland harvests it destroys the entire plant to regrow

### Expected behaviour

It should only harvest the tomato and not destroy the tomato plant

**Comment by Direwolf20-MC** [comment]
Unfortunately theres no way for me to "know" these plants behave this way, as they are entirely custom concepts.
