### ISSUE TITLE
[Enhancement/Suggestion] Improved cycling selection

### ISSUE THREAD

**Issue by antrobot1234** [Direwolf20-MC/JustDireThings#33]
As it stands, the selection menu on blocks can be cumbersome. A good example of this is the swapper block's entity selection. 
![image](https://github.com/Direwolf20-MC/JustDireThings/assets/21179158/5fa4ad1b-9775-4373-97e4-b5b35e07840b)
I have two suggestions that I could see helping to mitigate this problem

1. allow the user to shift+left click to cycle in the opposite direction. This is a fairly straightforwards suggestion but would help fix the problem of "missing" your selection and having to cycle back around to get it.
2. A significantly more in depth fix to this problem would involve some sort of selection "dropdown". I have created an illustration to help demonstrate my suggestion. 
![selection dropdown](https://github.com/Direwolf20-MC/JustDireThings/assets/21179158/036b372f-cf01-4629-badb-593b98d8f224)
if the user right clicks, a drop down will appear next to the selection. the user can then select which specific option they want from this dropdown. if the user clicks off of the menu or moves their mouse away, the drop down will dissapear. the current selection is highlighted in blue, and the current selection menu will have a blue tint on the selector UI element.

the user can also scroll to select when in this mode, or use the arrow keys + enter for a keyboard only interaction.

**Comment by Direwolf20-MC** [comment]
I'll likely add a right click to cycle backwards :)

**Comment by Direwolf20-MC** [comment]
You can now right click these buttons and they'll go 'backwards' 

https://github.com/Direwolf20-MC/JustDireThings/commit/cc360e3125e9da3e04b9c77a7b3ac53e7794ec91
