### ISSUE TITLE
[Enhancement/Suggestion] Cannot make even-numbered selections with advanced blocks.

### ISSUE THREAD

**Issue by antrobot1234** [Direwolf20-MC/JustDireThings#34]
As it stands, there is no way for the user to specify an even numbered selection boundary with the advanced blocks. I have 3 potential solutions that could achieve this
1. A toggle that enables "offset center" this makes the center of the radius in between blocks rather than in the center of a block
![example(1)](https://github.com/Direwolf20-MC/JustDireThings/assets/21179158/5433604a-00b3-4773-9c33-7f2d8b011efd)
2. half-step radius. allow the user to specify radius in increments of 1/2 rather than 1. (E.G. 0 is one block selected. 0.5 is 2 blocks selected. 1 is 3 blocks selected)
3. half-step offset. similar to the 2nd suggestion, but with the offset instead of the radius. a half offset would be in between two blocks rather than in the center. there would have to be some modification to how the radius works for this to make sense.

**Comment by Direwolf20-MC** [comment]
Yea i'm considering swapping to 1/2 increment radius. Or maybe going like building gadgets, and specifying a start and then a number of blocks in each direction. I haven't decided yet :).

**Comment by Direwolf20-MC** [comment]
Resolved :)
