### ISSUE TITLE
[Suggestion] add a toggle for the adv. dropper's filter ordering functionality.

### ISSUE THREAD

**Issue by antrobot1234** [Direwolf20-MC/JustDireThings#35]
While the filter ordering functionality (the feature that makes it so the dropper won't drop unless all items in the filter exist) is useful, it makes it so you can't treat it as a basic filter. as such, I suggest adding a toggle here
![image](https://github.com/Direwolf20-MC/JustDireThings/assets/21179158/8dafef62-0467-44d0-a23b-f19f3415b100)
that toggles the functionality. when disabled, any item in the filter will be allowed to drop, even if others in the filter don't exist.

the toggle could be labeled ["any"/"all"].

**Comment by Direwolf20-MC** [comment]
What benefit would there be to the 'any' mode? Why would you want to filter the dropper? If the item doesn't match the filter, it would just get stuck in the dropper? Instead you should filter what goes into it with a designated piping mod or something. 

Can you think of a use case for filtering in any mode?
