### ISSUE TITLE
[Bug(?)] Filter does not affect item insertion.

### ISSUE THREAD

**Issue by antrobot1234** [Direwolf20-MC/JustDireThings#36]
If you set up a filter for a block (such as for the block placer), then items from outside the filter can still be inserted through hoppers/other methods. I am not sure whether or not this is intended behavior, but if it is, I would suggest changing it so only filtered items are allowed to be inserted. this is especially important for the block placer, as it has a single slot. if the wrong item gets inserted into it, it will basically be useless since no other items are allowed in and it cannot use the item in its slot.

**Comment by Direwolf20-MC** [comment]
I don't think any of my blocks that accept items filter on which item can be used.  All of their filters do something else - like the placer determines where the blocks you give it can be placed, not which blocks can be placed. 

I leave it up to the player to insert the correct items :).   LaserIO should help!
