### ISSUE TITLE
[BUG] Ad Astra coal generator consumes fuel canister

### ISSUE THREAD

**Issue by AllieWade** [Direwolf20-MC/JustDireThings#40]
As the title says. I know it's probably on Ad Astra's side but I thought I'd mention it anyway.

Unfortunately when I shift-clicked my fuel canister into an Ad Astra coal generator, it was eaten. I'm in mourning, I had over a thousand fuel in it. 😂 I got like 4k RF total.

Thank you for this fantastic mod, I'm enjoying it.

**Comment by Direwolf20-MC** [comment]
Yup unfortunately thats definitely on Ad Astra's side.  They need to return the returned item from their furnace (Like a lava bucket returns an empty bucket in a vanilla furnace).  Unfortunately theres no way I can detect this kind of thing in advance to prevent the item loss :(.  Its 100% a bug on their side.  

Have them reach out to me if they need any help! Thanks!

For reference, they need something like this:
https://github.com/Direwolf20-MC/JustDireThings/blob/main/src/main/java/com/direwolf20/justdirethings/common/blockentities/GeneratorT1BE.java#L175
