### ISSUE TITLE
Crash when right-clicking the click mode button

### ISSUE THREAD

**Issue by hRobert12** [Direwolf20-MC/JustDireThings#43]
Right-clicking on the click mode button (to cycle backwards) in the simple or advanced clicker causes the game to crash.

Crash report: [crash-2024-04-19_09.51.40-client.txt](https://github.com/Direwolf20-MC/JustDireThings/files/15043513/crash-2024-04-19_09.51.40-client.txt)

**Comment by Direwolf20-MC** [comment]
Resolved - thanks! :)
