### ISSUE TITLE
Swappers can swap blocks in protected areas

### ISSUE THREAD

**Issue by hRobert12** [Direwolf20-MC/JustDireThings#45]
Both the simple and advanced swapper can swap blocks inside areas that you normally cannot place or break blocks in (protected areas).

### Steps to reproduce

1. Approach the edge of the protected area (only tested against FTB chunks, but should work against most land/region protection mods).
2. Place the swapper at the very edge of this area (i.e. the first block outside of the protected area). A simple swapper will need to be facing toward the protected area, while an advanced swapper will need to be configured to grab the desired area inside the protected area. Then pair this swapper with another one somewhere else.
3. Activate either swapper.

### Expected Behavior

The blocks inside the protected area are not swapped.

### Actual Behavior

The blocks are swapped.

#### MC & Mod

Minecraft: 1.20.4
NeoForge: 20.4.232
Just Dire Things: 0.9.9

#### Protection mod & its dependencies

FTB Chunks: 2004.1.2
FTB Teams: 2004.1.2
FTB Library: 2004.2.2
Architectury: 11.1.17

**Comment by Direwolf20-MC** [comment]
I suspected that might be the case. :). 

I need to get FTB into my dev env to test this stuff :). I’ll get to work fixing it.

**Comment by Direwolf20-MC** [comment]
Resolved in: https://github.com/Direwolf20-MC/JustDireThings/commit/807baae8bf10482f6dd8a64989359af6907f9afc
