### ISSUE TITLE
Paxel's cannot strip logs

### ISSUE THREAD

**Issue by thiccccccccccccccccccccccccccccc** [Direwolf20-MC/JustDireThings#46]
It would be nice if the paxels could strip logs. Only the axes can do it currently.

**Comment by GordonHollow** [comment]
And also paxels don't make path on dirt

like every mod adding paxels always forgot to add this tool features

**Comment by Direwolf20-MC** [comment]
Finally got around to addressing this :).  It'll be fixed in the next version
