### ISSUE TITLE
[Suggestion] Ability to use curios in certain machines

### ISSUE THREAD

**Issue by edotenseilove** [Direwolf20-MC/JustDireThings#51]
Firstly I would like to thank you for such an amazing mod which does a lot of useful and unique things that no other or a minimal number of mods can do.

Secondly I have a suggestion. I am an enjoyer of machines using tools to do things and therefore benefit from their abilities and enchantments. There are not many mods that can do this I do recall the pedestals mod and modular golems but still there are not many of them. Now I think that players often mine and kill things by themselves without relying on machines since they do not have them. They might stumble upon a useful curio that might help them by providing useful effects like +level of looting or fortune, specific type of damage amplification (for example bonus to attack damage or 
doing fire damage and other effects on hit) and so on. Now when the early game is over they switch to using machines and in most cases they never use the curios again due to the limitations of the machines like their inability to use curios (same case with using the tools and using enchantments but thanks to your mod this is no longer an issue).

Now my suggestion is to add the possibility of using curios in machines so that they are still useful and not just being dumped to a storage system or eternally equipped on a player and never used. 

The only mod that I know of that can benefit from curios are the modular golems which sadly only supports creating mob farms and nothing else.

Have a great day.

**Comment by Direwolf20-MC** [comment]
Its a neat idea, but the curios api's future is a little uncertain at the moment. It should be possible, and something I might consider in the future, but theres a lot of other stuff I'd like to add thats higher on the priority list.  I'll add this to my todo list to look into though :)

Thanks for the suggestion!
