### ISSUE TITLE
Crash with Simple Fuel Generator in NeoForge 1.20.6

### ISSUE THREAD

**Issue by NicholasRB** [Direwolf20-MC/JustDireThings#55]
Hi again Dire,
Found that the fuel generator JustDireThings has is crashing the game the second you try putting any burnable in the furnace. Not really sure why it is doing this, but just wanted to let you know. I've got the log below

Log:
[latest.log](https://github.com/Direwolf20-MC/JustDireThings/files/15284897/latest.log)

**Comment by Direwolf20-MC** [comment]
Hey thanks for the report! I just fixed this the other day actually. I’ll get it released shortly :)

this commit should have fixed it:
https://github.com/Direwolf20-MC/JustDireThings/commit/970cd0bdd43168a8e647f041ae07646bd276b67b
