### ISSUE TITLE
[Suggestion] Energy Transmitter Upgrades

### ISSUE THREAD

**Issue by Thorinori** [Direwolf20-MC/JustDireThings#57]
I believe it would be nice to have some way to increase particularly the transfer rate of Energy Transmitters. I find I REALLY like them in general, much more than having direwire everywhere, so combining LaserIO + Energy Transmitters has been nice. The downside is if any machine draws too much power though, the transmitter can't handle it. Having a way to increase its throughput would be very nice.

**Comment by Direwolf20-MC** [comment]
I’ll likely be making a tier 2 version ;)

**Comment by Thorinori** [comment]
Even better! Excited to see it, been loving the mod in general! Combining it with entangled blocks, laserio, and mekanism it feels like I can do just about everything. Currently making a base I think you would love, bunch of modular 9x9's in the sky making a big complex.

**Comment by Direwolf20-MC** [comment]
I am honestly really glad to hear it! If you have any other suggestions or ideas for additions feel free to let me know. :)

**Comment by Thorinori** [comment]
Only other suggestion off the top of my head would be enable the lava repairing on Blazegold equipment even if the other powers are turned off. I tend to keep them off so I don't accidentally eat up durability, but they can't repair in lava unless it is toggled on (They don't get destroyed in lava still though which is nice, otherwise I would be on pick 10 or something by now because I keep forgetting to re-enable it to repair)
