### ISSUE TITLE
Crash when entering portal

### ISSUE THREAD

**Issue by cameronkh** [Direwolf20-MC/JustDireThings#64]
Crashed when trying to enter portal before placing the other portal
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "com.direwolf20.justdirethings.common.entities.PortalEntity.level()" because the return value of "com.direwolf20.justdirethings.common.entities.PortalEntity.getLinkedPortal()" is null

**Comment by Direwolf20-MC** [comment]
Resolved :) will be fixed in the next update. Thanks!
