### ISSUE TITLE
(Suggestion) Config for More expensive Goo Crafting Recipes

### ISSUE THREAD

**Issue by Inonedn** [Direwolf20-MC/JustDireThings#67]
I think the goo recipes are too cheap, and can easily allow you to get incredibly overpowered gear very quickly, throwing off balance very easily. I think it would be nice for a config to change the recipe to be more expensive and balanced

**Comment by Direwolf20-MC** [comment]
Most mod packs use data packs or another mod to edit recipes. I don't think a config for recipe changes is a thing that's usually done :).
