### ISSUE TITLE
The mod fails to load on NeoForge 1.21

### ISSUE THREAD

**Issue by Steinzu** [Direwolf20-MC/JustDireThings#70]
MC Version : 
1.21

Mod Version :
Just Dire Things 0.11.2

NeoForge Version : 
21.0.37-beta

Issue : 
JDT fails to load on NeoForge versions above 21.0.30-beta, not an isolated issue, Architectury has a similar [issue](https://github.com/architectury/architectury-api/issues/522).

Cause (?) : 
Breaking changes starting from NeoForge 21.0.31-beta

![image](https://github.com/Direwolf20-MC/JustDireThings/assets/104737710/32c7f44e-b2a4-4481-b447-b512e6899ed5)

**Comment by Direwolf20-MC** [comment]
I’ll get on it asap. By end of week likely :)

**Comment by Direwolf20-MC** [comment]
Can you try upgrading Neoforge to beta 40 and see if it  still happens? I just updated mine and it seems to be fine?

**Comment by Direwolf20-MC** [comment]
Gotcha, I found the issue :) Working on a fix. Shouldn't be TOO long, hopefully later today

**Comment by Direwolf20-MC** [comment]
Resolved in the latest version :) its heading up to curseforge now
