### ISSUE TITLE
[BUG] Can't rename teleport points with the Advanced Portal Gun

### ISSUE THREAD

**Issue by Steinzu** [Direwolf20-MC/JustDireThings#71]
MC Version : 1.21
NeoForge Version : 21.0.42-beta
Just Dire Things Version : 0.11.4

Issue : 
When using the Advanced Portal Gun, while in the GUI, it is not possible to rename a favorite location's name.
The "Save and Close" button is not clickable.

![image](https://github.com/Direwolf20-MC/JustDireThings/assets/104737710/4dce86ca-4abd-4fb5-a17c-859f37ebb02e)

_(Also, unrelated but maybe adding issue templates for bugs and feature requests could be useful, Mekanism's one is pretty good IMO)_

**Comment by Direwolf20-MC** [comment]
Can't reproduce with just JEI and JDT installed on forge 21.0.42-beta. 

Is there maybe another mod causing a conflict?

**Comment by Direwolf20-MC** [comment]
Yea you're doing it right - thats crazy! Anything in the logs?
