### ISSUE TITLE
[BUG] Crash when mining any block with a Celestigem paxel (Neoforge) (Mod Version 0.11.2)

### ISSUE THREAD

**Issue by ThatElektrika** [Direwolf20-MC/JustDireThings#72]
Whenever I mine any block, the game crashes. 
[crash-2024-06-29_00.45.36-server.txt](https://github.com/user-attachments/files/16038771/crash-2024-06-29_00.45.36-server.txt)

**Comment by ThatElektrika** [comment]
As is listed in the title, I am not using the latest. This version is in a modpack that cannot be updated to a newer version of Neoforge yet.

**Comment by ThatElektrika** [comment]
Only if a newer version of Neoforge is used for the fix.

**Comment by Direwolf20-MC** [comment]
It will be. The fixes put in 0.11.4 require neoforge 40 beta or above. 

I’ll look into this sometime soon :)

**Comment by Direwolf20-MC** [comment]
Also please try the latest version of the mod. Now that I look at the crash report I’m almost sure I fixed this.

in short neoforge changed stuff. The newest version of the mod should be all fixed. Can you test and let me know ?

**Comment by ThatElektrika** [comment]
Ok, thank you!
Also it appears to be with ALL tools (even swords)
same for Eclipse tier as well, maybe its a power tool issue? idk

**Comment by ThatElektrika** [comment]
> Also please try the latest version of the mod. Now that I look at the crash report I’m almost sure I fixed this.
> 
> in short neoforge changed stuff. The newest version of the mod should be all fixed. Can you test and let me know ?

Can't do that. The mod is for a version of Neoforge with breaking changes thatll break the mods in the modpack.

**Comment by ThatElektrika** [comment]
I'm playing TNP Limitless 8 which released less than a week ago

**Comment by Direwolf20-MC** [comment]
Yes the problem is the crash is caused by a change neoforge made. So you’ll NEED to update neoforge for this to work. There’s no way around it sadly.

**Comment by ThatElektrika** [comment]
that's unfortunate
