### ISSUE TITLE
[Suggestion] Add a config option for Ore scanner

### ISSUE THREAD

**Issue by Kevin-Marsh** [Direwolf20-MC/JustDireThings#75]
Would it be possible to create a config option for the Ore scanner function to disable it on the tools? This would allow modpack makers to customise and remove the function in favour of other scanning methods such as potions master without effecting any of the tools.

**Comment by Direwolf20-MC** [comment]
Are you a pack maker who wants to do this, or are you suggesting it generically ;)

**Comment by Kevin-Marsh** [comment]
I am helping out with developing All the mods 10. Potions Master is what is typically used in the pack. I was suggesting as there typically aren't that many extra ore scanner abilities and they tend not to just generically show everything rather needing to be targeted and a little later game than just having iron available. Everyone is loving the mod by the way.

**Comment by Direwolf20-MC** [comment]
Sounds good :) yea I’ll add some kind of abilities config options then.

**Comment by Direwolf20-MC** [comment]
Added a config for all abilities :).
