### ISSUE TITLE
[Suggestion] The ability to display a creature catcher that has a mob inside it.

### ISSUE THREAD

**Issue by DawnFayrie** [Direwolf20-MC/JustDireThings#76]
While the creature catchers has a mob instead when viewed in the hotbar they have a nice visual, akin to a snowglobe.  The ability to be able to set these down as is and display them in world would give some insteresting design options similar to Ars Nouveau and its containment jars, though doesn't need the farming ability.

**Comment by Direwolf20-MC** [comment]
I think they work in Item Frames - but a way to place them in world might be cool. I'll add it to the list of nice to haves :)
