### ISSUE TITLE
[Suggestion] For the advanced portal gun coordinate editing.

### ISSUE THREAD

**Issue by Steinzu** [Direwolf20-MC/JustDireThings#79]
https://github.com/Direwolf20-MC/JustDireThings/issues/77#issuecomment-2198731266

Saw that you were trying find a balanced way to do it, I was thinking about adjusting the coordinates based on the current saved one and it consumes portal fluid depending on how far you are from it, this solution adds both a cap to how far you can go and a cost to it.

Ex : 
Editing from -500 70 600 to -700 65 400 costs X amount of portal fluid.
While from -700 65 400 to -750 65 410 costs 0.2X portal fluid.

**Comment by Direwolf20-MC** [comment]
I’m considering a block that can create a portal that lets you specify the coordinates. So you need a block to dial up a position. And like you said consuming a lot of portal fluid.
