### ISSUE TITLE
Duplicated Dimensional Chests

### ISSUE THREAD

**Issue by djnifos** [Direwolf20-MC/JustDireThings#82]
Loader:
Neoforge - 21.0.43

Mods used to reproduce:
DimStorage-1.21.9.0.0
EdivadLib-1.21-3.0.0
justdirethings-0.11.6
jei-1.21-neoforge19.0.0.14

Steps to reproduce:
Place down dimchest, break with a pickaxe from Just Dire things, get two dimchests
Problem does not exist with vanilla pickaxes. Tried on Enabled and Disabled, problem persists.

**Comment by Direwolf20-MC** [comment]
I'll look into it :).

**Comment by Direwolf20-MC** [comment]
I've created a bug report over on DimStorage's side - I'm not sure which of us is doing it wrong :)

https://github.com/Edivad99/DimStorage/issues/58

**Comment by Direwolf20-MC** [comment]
Resolved in the latest Dim Storage
