### ISSUE TITLE
(Suggestion) Add limitations to Creature Catcher

### ISSUE THREAD

**Issue by Inonedn** [Direwolf20-MC/JustDireThings#86]
atm, it can capture almost ANY mob in the game, including bosses, which would be extremely overpowered, especially if used on a Warden or Wither, so there should be a HP limit of the mob it can capture. It shouldn't be able to capture mobs with 50 or more HP.

**Comment by Direwolf20-MC** [comment]
Theres an entity tag called 'Creature Catcher Deny' that mod pack authors can use to block mob captures.
