### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by Inonedn** [Direwolf20-MC/JustDireThings#90]
[crash-2024-07-07_21.27.38-server.txt](https://github.com/user-attachments/files/16121743/crash-2024-07-07_21.27.38-server.txt)

**Comment by Direwolf20-MC** [comment]
What version of neoforge?

**Comment by Inonedn** [comment]
latest, 0.76

**Comment by Direwolf20-MC** [comment]
Guessing something changed. I’ll check it out.

**Comment by Inmataw** [comment]
i have the same issue 
[crash-2024-07-09_16.22.32-server.txt](https://github.com/user-attachments/files/16152062/crash-2024-07-09_16.22.32-server.txt)

**Comment by Direwolf20-MC** [comment]
Sorry for the delay I’ll get to this soon :)

**Comment by Inmataw** [comment]
Thank you, I really appreciate your work, your mod is amazing :D

**Comment by Direwolf20-MC** [comment]
Resolved in 0.11.9 - Just pushed it to Curseforge so give it a minute or 2 :)
