### ISSUE TITLE
[Suggestion] Bump ferricore up to diamond pickaxe level

### ISSUE THREAD

**Issue by Kevin-Marsh** [Direwolf20-MC/JustDireThings#91]
At the moment your tools provide an effective alternate path to bypass vanilla tools. You can make primogel fairly easily with stone materials which means that you could go stone - ferricore. This progression is hampered without the ability to mine obsidian since you can't go from ferricore to blazegold without getting a diamond pick or building a speedrunner portal to gain access to the nether. Bumping this initial level to diamond tier or otherwise including a method for ferricore to be able to break obsidian would allow access to the nether and preserve progression solely in the mod.

**Comment by Direwolf20-MC** [comment]
I considered this but didn’t want to break vanilla progression. If I did it I would want to make diamonds a component.
