### ISSUE TITLE
[Bug] Celestigem equipment crashing worlds if used in item users.

### ISSUE THREAD

**Issue by Kevin-Marsh** [Direwolf20-MC/JustDireThings#95]
We are having an issue where celestigem tools are crashing games when used in item users. There are two examples we have come across so far. If you place a celestigem hoe in a harvester pylon from the Pylons mod and another where a user placed a celestigem sword in an advanced clicker. The pylon issue has been replicated in newest but I haven't managed to replicate the sword issue from a quick once over.

Pylon crash log: https://mclo.gs/rjNrjQn
Clicker crash log: https://mclo.gs/kLROR8y#L5

Pack: ATM10 1.0.9
Neoforge: 21.0.64
JDT version: 0.11.7

Pylons replication was latest neoforge and latest JDT.

**Comment by Direwolf20-MC** [comment]
Thanks for the report - this'll be fixed in the next version for 1.21 :)
