### ISSUE TITLE
Suggestion: Add a JEI/EMI entry for Ore drops

### ISSUE THREAD

**Issue by MuteTiefling** [Direwolf20-MC/JustDireThings#97]
Pretty minor request, but I think it'd be handy to see that the raw ores/coals come from their respective crystal. This way a player can trace back from the final material all the way to the goo transmutation.

For example, I was able to add them to EMI with their resource pack system, but it'd be nice if they were in a tab by default: 

![image](https://github.com/user-attachments/assets/65543d3a-0cab-487c-81af-039d732da474)

**Comment by Direwolf20-MC** [comment]
Yea I'd likely have to create a custom recipe lookup - because this kind of thing doesn't generally exist in JEI by default.  I'll add it to the 'nice to have' list :)
