### ISSUE TITLE
[Feature Request] Configurable Eclipse Gate Range

### ISSUE THREAD

**Issue by micrwvae** [Direwolf20-MC/JustDireThings#98]
love that feature but sometimes the rage is just too large

would it be possible to add a slider to the eclipse gate to configure how far the blocks get ghosted, like the armor has for the effects

**Comment by Direwolf20-MC** [comment]
Great minds think alike :) I actually realized this was something I wanted to add a few days ago, because I thought it might be cool to make a door with a clicker and the eclipsegate wand. I have plans to implement it in the next version. 

Thank you for the suggestion! :)

**Comment by micrwvae** [comment]
oh perfect 
thanks for the hard work![image](https://github.com/user-attachments/assets/bea8cf43-b4fa-43d6-8907-e2db38c455a4)
